"""Auto-generated run_order for integration — 36 BrainMechanism subclasses."""

INTEGRATION_RUN_ORDER = [
    "AllostaticPredictiveAnticipator",
    "AnteriorCommissureLimbicBridge",
    "AutonoeticNarrativeSelf",
    "BasalGangliaThalamoCorticalLoopFinalIntegrator",
    "CerebellarCorticalPredictiveLoop",
    "CingulumBundleAssociativeBridge",
    "ClaustrumGlobalConsciousness",
    "CorpusCallosumFullBridge",
    "CorticoThalamicPrecisionTuner",
    "CrossLayerContradictionResolver",
    "DynamicIncompletenessEnforcer",
    "FornixHippocampalCingulateBridge",
    "GlobalWorkspaceIntegrator",
    "HierarchicalTopDownBottomUpEquilibrator",
    "HypothalamicCorticalBottomUpDrive",
    "IdentityConsciousnessGuardian",
    "InternalCapsuleFrontalBGThalamic",
    "InternalCapsuleMotorFinalOutput",
    "InteroExteroceptiveMerger",
    "InteroceptiveGradient",
    "LongRangeDendriticIntegrator",
    "MammillothalamicTractPathway",
    "MedialForebrainBundleDopamine",
    "MetaAwarenessSelfObserver",
    "MidCingulateSubgenualBridge",
    "NetworkOscillationGlobalBalancer",
    "PapezCircuitEmotionalMemoryIntegrator",
    "PrefrontalAmygdalaTopDownRegulation",
    "RewardPredictionErrorIntegrator",
    "SalienceDefaultExecutiveToggling",
    "SomatosensoryCortexBodySchema",
    "StriaTerminalisAmygdalaHypothalamus",
    "TemporoParietoOccipitalJunctionAssembler",
    "ThalamoClaustrumGlobalWorkspace",
    "ThetaGammaCrossFrequencyBinding",
    "VentralDorsalStreamUnification",
]

assert len(INTEGRATION_RUN_ORDER) == 36
