"""Auto-generated run_order for neocortical — 50 BrainMechanism subclasses."""

NEOCORTICAL_RUN_ORDER = [
    "AngularGyrusMultimodal",
    "AnteriorCingulateCognitive",
    "AnteriorInferiorTemporalGyrus",
    "AnteriorInsulaSalienceAttentional",
    "AnteriorTemporalPoleSemantic",
    "AssociativeCorticalLongRange",
    "BrocaAreaMotorSpeech",
    "CingulateMotorArea",
    "DorsalPrefrontalCentralExecutive",
    "DorsolateralPrefrontalDorsal",
    "DorsolateralPrefrontalVentral",
    "FrontopolarProspectiveSimulator",
    "FusiformFaceArea",
    "InferiorFrontalGyrusTriangular",
    "InferiorParietalLobuleSensorimotor",
    "LateralOrbitofrontal",
    "LayerIIIIIAssociator",
    "LayerIMolecularIntegrator",
    "LayerVIThalamicModulator",
    "LayerVOutputProjector",
    "MedialPrefrontalSelfReflection",
    "MiddleFrontalGyrusDLPFClateral",
    "MiddleTemporalGyroscopic",
    "MotorCortexPrimaryOutput",
    "OccipitalPrimaryVisualV1",
    "OccipitalV2BoundaryProcessing",
    "OccipitalV3DepthProcessing",
    "OrbitofrontalRewardValuator",
    "ParafovealVisualProcessing",
    "PostcentralGyrusPrimarySomato",
    "PosteriorCingulateMemoryAttention",
    "PosteriorInferiorTemporalGyrus",
    "PosteriorParietalCortexIntegration",
    "PosteriorSuperiorTemporalGyrus",
    "PrecuneusSelfReflection",
    "PrefrontalCortexLayerSpecific",
    "PremotorSupplementaryMotorArea",
    "RetrosplenialCortexSceneProcessing",
    "SecondaryVisualCorticalStream",
    "SensoryCorticalColumnProcessor",
    "SuperiorFrontalGyrusPlanning",
    "SuperiorParietalLobuleReaching",
    "SupramarginalGyrusManipulation",
    "TemporoOccipitalVisualAssembler",
    "TemporoParietoOccipitalJunction",
    "V4ColorAndForm",
    "VentralVisualStreamObject",
    "VentrolateralPrefrontalInferior",
    "VentromedialPrefrontalEmotional",
    "WernickeAreaSemanticComprehension",
]

assert len(NEOCORTICAL_RUN_ORDER) == 50
