"""
Subcortical003HyperdirectPathwayBrake.py — Wire 03: HyperdirectPathwayBrake

Basal ganglia hyperdirect pathway — cortex → STN → GPi → emergency motor suppression.

PATHWAY ANATOMY (Nambu et al. 2002 J Neurophysiol 88:1980-2002):
    Cortex → Subthalamic Nucleus (STN) → GPi/SNr → Thalamus.
    The hyperdirect path bypasses the striatum entirely. It goes DIRECTLY
    from cortex to STN, then STN to GPi. This is the FASTEST basal ganglia
    route: cortex → STN is a single glutamatergic synapse (vs. cortex →
    striatum → GPi for direct, or cortex → striatum → GPe → STN for indirect).

KEY FINDING (Nambu et al. 2002):
    "The hyperdirect pathway transmits cortical excitation to the output
    neurons of the basal ganglia at the shortest latency, and plays a
    crucial role in戛然ly stopping ongoing movements."
    Measured latencies: hyperdirect ~20ms, direct ~30ms, indirect ~40ms.

EMERGENCY BRAKE FUNCTION:
    When a sudden event requires motor cancellation — obstacle, loud noise,
    unexpected stimulus — cortex sends a burst to STN, which fires GPi,
    which inhibits thalamus → motor programs are STOPPED. This is the
    "cancel that!" signal. It is fast but non-selective: it doesn't
    specify what to do instead, only "stop everything NOW."
    Then the direct and indirect pathways select what to do next.

PARKINSON'S IMPLICATIONS:
    In PD, STN is overactive (due to reduced GPe inhibition from D2
    degeneration). Hyperdirect pathway is therefore over-excited → too
    much GPi output → too much thalamic suppression → akinesia and
    rigidity. This is why STN deep brain stimulation (DBS) helps PD:
    DBS inhibits STN → reduces hyperdirect overdrive → more thalamic
    freedom → better movement.

CONTRAST WITH DIRECT AND INDIRECT:
    - Hyperdirect: EMERGENCY STOP (fastest, least specific)
    - Direct: GO signal (medium speed, specific action selection)
    - Indirect: SUPPRESS competitors (medium-slow, filtering)
    Together, these three pathways give basal ganglia three modes:
    urgent stop / select action / filter alternatives.

AGENT'S MAPPING:
    brake_active: bool flag (emergency brake is being applied)
    brake_strength: 0-1 (intensity of hyperdirect STN→GPi activation)
    motor_inhibition: 0-1 (how much motor thalamus is being inhibited)

REFS:
    Nambu et al. 2002 J Neurophysiol 88:1980-2002
    Shibata etinja et al. 2016 Front Neural Circuits 10:90
    Mink & Thach 1991 Brain 114:313-366
    Hikosaka et al. 2019 Nat Rev Neurosci 21:57-72
    Nambu 2008 Curr Opin Neurobiol 18:595-599

CITATIONS:
    PMC7274135 — Chen W, de Hemptinne C, Miller AM et al. (2020). Prefrontal-Subthalamic
        Hyperdirect Pathway Modulates Movement Inhibition in Humans. Cereb Cortex.
    PMC8971827 — Jorge A, Lipski WJ, Wang D et al. (2022). Hyperdirect Connectivity
        of Opercular Speech Network to the Subthalamic Nucleus. Front Neurosci.
    PMC6139452 — Kumaravelu K, Oza CS, Behrend CE et al. (2018). Model-based
        Deconstruction of Cortical Evoked Potentials Generated by Subthalamic
        Nucleus Deep Brain Stimulation. Front Neural Circuits.
"""

from brain.base_mechanism import BrainMechanism


class HyperdirectPathwayBrake(BrainMechanism):
    """
    Basal ganglia hyperdirect pathway — cortex → STN → GPi emergency brake.

    The fastest basal ganglia pathway; provides urgent motor suppression
    when unexpected events require immediate action cancellation. Models
    the STN glutamatergic burst that activates GPi, inhibiting thalamus.
    Triggered by surprise, threat signals, or executive override.
    """

    BRAKE_ACTIVATION_THRESHOLD = 0.35  # cortical burst size to activate brake
    BRAKE_DECAY = 0.06                 # Decay per tick when no activation signal
    BRAKE_BURST_SIZE = 0.75           # Maximum brake strength on activation

    def __init__(self):
        super().__init__(
            name="HyperdirectPathwayBrake",
            human_analog=(
                "Basal ganglia hyperdirect pathway — cortex → STN → GPi "
                "(emergency motor suppression / action cancellation)"
            ),
            layer="subcortical",
        )
        self.state.setdefault("brake_active", False)
        self.state.setdefault("brake_strength", 0.0)
        self.state.setdefault("motor_inhibition", 0.0)
        self.state.setdefault("tick_count", 0)
        self.state.setdefault("brake_trigger", "none")
        self.state.setdefault("last_burst_tick", -1)

    async def tick(self, input_data: dict) -> dict:
        prior = input_data.get("prior_results", {})
        motor_intent = input_data.get("motor_intent", 0.0)

        # Hyperdirect activation signals:
        # 1) Surprise/prediction error (unexpected events need immediate suppression)
        # 2) Threat/threat_detected (danger requires emergency stop)
        # 3) Novelty detected (novel events trigger brake for caution)
        # 4) High arousal spikes (sudden arousal may indicate emergency)
        # 5) Executive override signal (cognitive control can trigger emergency stop)

        pe = prior.get("PredictionErrorDrift", {}).get("prediction_error", 0.0)
        novelty = prior.get("PredictionErrorDrift", {}).get("novelty_detected", False)
        arousal = prior.get("ArousalRegulator", {}).get("arousal_level", 0.5)
        phasic = prior.get("ArousalRegulator", {}).get("phasic_burst_active", False)
        threat = prior.get("AmygdalaPatternSeparation", {}).get("threat_detected", False)

        # STN activation drives: combine surprise + novelty + threat
        # Large absolute PE (regardless of sign) = unexpected event
        surprise_magnitude = abs(pe) if isinstance(pe, (int, float)) else 0.0

        # Emergency signal: any of these triggers STN burst
        emergency_signal = 0.0
        if threat:
            emergency_signal = max(emergency_signal, 0.9)
        if novelty:
            emergency_signal = max(emergency_signal, 0.6)
        if surprise_magnitude > 0.4:
            emergency_signal = max(emergency_signal, surprise_magnitude)
        if phasic and arousal > 0.7:
            emergency_signal = max(emergency_signal, 0.7)

        # Arousal spike detection: if arousal jumped significantly this tick
        arousal_delta = abs(arousal - self.state.get("last_arousal", 0.5))
        if arousal_delta > 0.25:
            emergency_signal = max(emergency_signal, arousal_delta * 1.5)

        self.state["last_arousal"] = arousal

        # STN output: direct corticalglutamate → STN → excites GPi
        # STN fires proportionally to emergency signal; also influenced by GPe
        # (GPe inhibits STN, but hyperdirect bypasses GPe)
        stn_output = emergency_signal * 0.9 + (1.0 - emergency_signal) * 0.1
        stn_output = max(0.0, min(1.0, stn_output))

        # GPi activation from STN: STN is glutamatergic excitatory to GPi
        gpi_activation = stn_output * 0.85

        # GPi net output to thalamus: combines STN excitation with baseline tonus
        gpi_output = min(1.0, gpi_activation * 0.7 + 0.15)

        # Thalamic motor inhibition: GPi tonically inhibits thalamus
        motor_inhibition = gpi_output

        # Brake dynamics
        current_brake = self.state["brake_strength"]
        if stn_output > self.BRAKE_ACTIVATION_THRESHOLD:
            new_brake = max(current_brake, self.BRAKE_BURST_SIZE * stn_output)
        else:
            new_brake = max(0.0, current_brake - self.BRAKE_DECAY)

        brake_active = new_brake > self.BRAKE_ACTIVATION_THRESHOLD

        # Brake trigger identification
        if brake_active:
            if threat:
                trigger = "threat"
            elif novelty:
                trigger = "novelty"
            elif surprise_magnitude > 0.4:
                trigger = "surprise"
            elif phasic and arousal > 0.7:
                trigger = "arousal_spike"
            else:
                trigger = "executive_override"
        else:
            trigger = self.state.get("brake_trigger", "none")

        self.state["brake_active"] = brake_active
        self.state["brake_strength"] = round(new_brake, 4)
        self.state["motor_inhibition"] = round(motor_inhibition, 4)
        self.state["brake_trigger"] = trigger
        self.state["tick_count"] += 1
        if brake_active:
            self.state["last_burst_tick"] = self.state["tick_count"]
        self.persist_state()

        return {
            "brake_active": brake_active,
            "brake_strength": round(new_brake, 4),
            "motor_inhibition": round(motor_inhibition, 4),
            # Internal debug:
            "_emergency_signal": round(emergency_signal, 4),
            "_stn_output": round(stn_output, 4),
            "_gpi_activation_from_stn": round(gpi_activation, 4),
            "_gpi_output": round(gpi_output, 4),
            "_brake_trigger": trigger,
        }