"""
BeliefArchaeologyLayerAdapter — Auto-generated BrainMechanism adapter (from brain/ root)

WRAPS:
    brain.belief_archaeology.BeliefArchaeologyLayer

LAYER:
    integration

NOTE: Generated by scripts/brain_root_adapter_generator.py. The wrapped
class uses the old process(pirp_context) pattern; this adapter exposes
it via async tick(input_data) so the brain_runner can register it.
"""
import os
from pathlib import Path

from brain.base_mechanism import BrainMechanism
from brain.belief_archaeology import BeliefArchaeologyLayer


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".openclaw" / "workspace")))
    / "brain" / "agent.db"
)


class BeliefArchaeologyLayerAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around brain.BeliefArchaeologyLayer."""

    def __init__(self):
        super().__init__(
            name="BeliefArchaeologyLayer",
            human_analog="brain/ root BeliefArchaeologyLayer (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = BeliefArchaeologyLayer()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}
        prior = input_data.get("prior_results", {})
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}
        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}
        if isinstance(result, dict):
            output = result.get("BeliefArchaeologyLayer",
                                  result.get("belief_archaeology", result))
        else:
            output = {"value": result}
        if not isinstance(output, dict):
            output = {"value": output}
        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output
