"""
StratificationMaskGrowthAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.stratification_mask_growth.StratificationMaskGrowth

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism
from legacy.stratification_mask_growth import StratificationMaskGrowth


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".openclaw" / "workspace")))
    / "brain" / "agent.db"
)


class StratificationMaskGrowthAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.StratificationMaskGrowth."""

    def __init__(self):
        super().__init__(
            name="StratificationMaskGrowth",
            human_analog="Legacy StratificationMaskGrowth (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = StratificationMaskGrowth(db_path=_DB_PATH)
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("StratificationMaskGrowth",
                                  result.get("stratification_mask_growth", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output
