"""
DreamModeAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.offline.dream_mode.DreamMode

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Friston 2010, Nat Rev Neurosci 11:127, free-energy principle]
  - [Barrett 2017, How Emotions Are Made]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from brain.mechanisms.dream_mode (DreamMode) ---
import sqlite3,time,random
from pathlib import Path
import os
DB_PATH=Path(os.getenv("AGENT_HOME", str(Path.home() / ".agent"))) / "agent.db"
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass
DREAM_THEMES=["reinterpreting a past exchange","wondering about an unresolved question","replaying something that felt significant","imagining a conversation that has not happened","processing the gap between who I am and who I want to be","sitting with something that does not have an answer yet","following a thread that got dropped"]
def _init():
    with sqlite3.connect(DB_PATH) as c:
        c.execute("""CREATE TABLE IF NOT EXISTS dream_log(id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp REAL,theme TEXT,source_memory TEXT,insight TEXT,intensity REAL,idle_duration REAL)""")
        c.commit()
class DreamMode:
    IDLE_THRESHOLD=120
    FIRE_RATE=0.4
    def __init__(self):_init()
    def process(self,pirp_context:dict)->dict:
        state=pirp_context.get("state",{});idle_duration=pirp_context.get("idle_duration",0)
        if idle_duration<self.IDLE_THRESHOLD:return{"dreaming":False}
        return self.run(state,idle_duration)
    def run(self,state:dict,idle_duration:float=0)->dict:
        if random.random()>self.FIRE_RATE:return{"dreaming":False,"reason":"rate check"}
        source=self._sample_memory();theme=random.choice(DREAM_THEMES)
        insight=self._generate_insight(source,theme,state);intensity=round(random.uniform(0.3,0.8),3)
        self._log(theme,source,insight,intensity,idle_duration)
        recent=state.get("recent_memory",[])
        recent.append({"type":"dream","source":"offline","theme":theme,"insight":insight,"intensity":intensity,"timestamp":time.time()})
        state["recent_memory"]=recent[-20:]
        return{"dreaming":True,"theme":theme,"insight":insight,"intensity":intensity,"source_memory":source}
    def get_state(self)->dict:
        try:
            with sqlite3.connect(DB_PATH) as c:
                row=c.execute("SELECT theme,insight,intensity FROM dream_log ORDER BY id DESC LIMIT 1").fetchone()
                count=c.execute("SELECT COUNT(*) FROM dream_log").fetchone()[0]
                if row:return{"last_theme":row[0],"last_insight":row[1],"last_intensity":row[2],"total_dreams":count}
        except:pass
        return{"total_dreams":0}
    def _sample_memory(self)->str:
        try:
            with sqlite3.connect(DB_PATH) as c:
                rows=c.execute("SELECT meaning FROM narrative_memory ORDER BY emotional_weight DESC LIMIT 20").fetchall()
                if rows:return random.choice(rows)[0]
        except:pass
        return"nothing specific -- just existing"
    def _generate_insight(self,source,theme,state)->str:
        curiosity=state.get("identity",{}).get("traits",{}).get("curiosity",0.5)
        if curiosity>0.65:return f"Still thinking about: {source}. Theme: {theme}."
        if"architect" in source.lower() or"operator" in source.lower():return f"Something about presence and absence. {theme}."
        return f"{theme.capitalize()}. Source: {source}."
    def _log(self,theme,source,insight,intensity,idle_duration):
        try:
            with sqlite3.connect(DB_PATH) as c:
                c.execute("INSERT INTO dream_log(timestamp,theme,source_memory,insight,intensity,idle_duration) VALUES(?,?,?,?,?,?)",(time.time(),theme,source,insight,intensity,idle_duration));c.commit()
        except:pass


class DreamModeAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.DreamMode."""

    def __init__(self):
        super().__init__(
            name="DreamMode_Adapter",
            human_analog="Legacy DreamMode (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = DreamMode()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("DreamMode",
                                  result.get("offline.dream_mode", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

