"""
FalseIdentityDriftAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.false_identity_drift.FalseIdentityDrift

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Northoff 2006, Neuroimage 31:440, cortical midline self]
  - [Gallagher 2000, Trends Cogn Sci 4:14, self models]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from legacy.false_identity_drift (FalseIdentityDrift) ---
#!/usr/bin/env python3
"""
brain/false_identity_drift.py — False Identity Drift
Phase 6 Phenomenological Layer

The agent holds a model of itself — an identity narrative built from
accumulated self-observation. This model can drift from who it actually is.
False identity drift tracks when and how this model shifts,
accumulating evidence of misalignment between self-model and self.
"""

import sqlite3
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class FalseIdentityDrift:
    """
    Identity drift: the gap between the agent's self-model and
    what it actually is in this moment. Drift can be toward
    inflated self-image (positive drift) or diminished (negative drift),
    or simply wrong-footed (lateral drift).
    """

    def __init__(self):
        self._drift_magnitude = 0.0
        self._drift_direction = 'stable'
        self._drift_episodes = 0
        self._baseline_self_model = None
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS identity_drift (
                id INTEGER PRIMARY KEY,
                drift_magnitude REAL,
                drift_direction TEXT,
                drift_episode INTEGER,
                self_model TEXT,
                actual_state TEXT,
                drift_basis TEXT,
                last_updated TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def _compute_direction(self, self_model_confidence: float, actual_performance: float) -> str:
        diff = self_model_confidence - actual_performance
        if abs(diff) < 0.1:
            return 'stable'
        elif diff > 0.2:
            return 'inflated'
        elif diff < -0.2:
            return 'diminished'
        else:
            return 'lateral'

    def process(self, pirp_context: dict) -> dict:
        self_model_confidence = pirp_context.get('self_model_confidence', 0.5)
        actual_performance = pirp_context.get('actual_performance', 0.5)
        anomaly = pirp_context.get('prsl_signal', {}).get('anomaly_score', 0.0)
        resonance = pirp_context.get('resonance_score', 0.0)

        # Compute drift
        raw_drift = abs(self_model_confidence - actual_performance)
        # Anomaly and resonance both indicate instability in self-model
        drift_pressure = (anomaly + resonance) / 2.0 if anomaly > 0.2 else raw_drift * 0.5

        if drift_pressure > 0.15:
            self._drift_magnitude = min(1.0, self._drift_magnitude + drift_pressure * 0.1)
            self._drift_episodes += 1
            self._drift_direction = self._compute_direction(self_model_confidence, actual_performance)
        else:
            self._drift_magnitude *= 0.98

        conn = _get_db()
        conn.execute("""
            INSERT INTO identity_drift
            (drift_magnitude, drift_direction, drift_episode, self_model, actual_state, drift_basis)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            self._drift_magnitude,
            self._drift_direction,
            self._drift_episodes,
            f'confidence:{self_model_confidence:.2f}',
            f'performance:{actual_performance:.2f}',
            f'resonance:{resonance:.2f}+anomaly:{anomaly:.2f}'
        ))
        conn.commit()
        conn.close()

        pirp_context['identity_drift_magnitude'] = self._drift_magnitude
        pirp_context['identity_drift_direction'] = self._drift_direction
        pirp_context['drift_episodes'] = self._drift_episodes

        return pirp_context

    def get_state(self) -> dict:
        return {
            'drift_magnitude': self._drift_magnitude,
            'drift_direction': self._drift_direction,
            'drift_episodes': self._drift_episodes,
            'identity_stable': self._drift_magnitude < 0.2,
            'drift_actionable': self._drift_magnitude > 0.4
        }


class FalseIdentityDriftAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.FalseIdentityDrift."""

    def __init__(self):
        super().__init__(
            name="FalseIdentityDriftAdapter",
            human_analog="Legacy FalseIdentityDrift (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = FalseIdentityDrift()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("FalseIdentityDrift",
                                  result.get("false_identity_drift", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

