"""
IncompletenessContagionAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.becoming.incompleteness_contagion.IncompletenessContagion

LAYER:
    limbic

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.

CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Tsakiris 2017, Phil Trans R Soc B 372:20160002, body ownership]
  - [Seth 2013, Trends Cogn Sci 17:565, interoceptive predictive]

"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)

# === Inlined legacy implementation ===
import os

VERSION = "19.0B"

import logging
import re
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DB_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "brain" / "agent.db"
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass

# Contagion types
DESIRE_CONTAGION = "desire_contagion"
GAP_CONTAGION = "gap_contagion"
NARRATIVE_CONTAGION = "narrative_contagion"

# Unresolved tick threshold to trigger contagion
DESIRE_CONTAGION_THRESHOLD = 150   # ticks unresolved
GAP_CONTAGION_THRESHOLD = 120      # ticks + high recurrence
NARRATIVE_CONTAGION_THRESHOLD = 200  # ticks under pressure

# Stopping condition: ambient threshold
AMBIENT_THRESHOLD_TICKS = 800      # ticks without change
AMBIENT_THRESHOLD_DESIRE = 1200    # desires persist longer

# Contagion contribution to contagion_score
CONTAGION_SCORE_PER_EVENT = 0.15

# Maximum contagion events per tick to prevent overload
MAX_CONTAGION_PER_TICK = 2

# Minimum gap between contagion events of same source
CONTAGION_COOLDOWN_TICKS = 30

MDT = timezone(timedelta(hours=-6))


# ---------------------------------------------------------------------------
# IncompletenessContagion
# ---------------------------------------------------------------------------

class IncompletenessContagion:

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = Path(db_path) if db_path else DB_PATH
        self._initialize_tables()
        self._last_contagion_tick: dict = {}   # source_key -> tick
        self._contagion_score: float = 0.0

    # ------------------------------------------------------------------
    # Table init
    # ------------------------------------------------------------------

    def _initialize_tables(self):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS contagion_events (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        tick INTEGER,
                        timestamp TEXT,
                        contagion_type TEXT,
                        source_id TEXT,
                        source_text TEXT,
                        spawned_content TEXT,
                        intensity REAL
                    )
                """)
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS ambient_incompleteness (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        source_type TEXT,
                        source_key TEXT NOT NULL UNIQUE,
                        source_text TEXT,
                        sedimented_tick INTEGER,
                        timestamp TEXT,
                        residue_multiplier REAL DEFAULT 0.08,
                        witness_noted INTEGER DEFAULT 0
                    )
                """)
                conn.commit()
        except Exception as e:
            logger.error(
                "IncompletenessContagion: table init failed — %s", e
            )

    # ------------------------------------------------------------------
    # Tick-level process
    # ------------------------------------------------------------------

    def process(self, pirp_context: dict) -> dict:
        """
        BrainMechanism-compatible process() method.

        Scans for contagion conditions. Generates contagion events.
        Checks for ambient threshold crossings.
        Returns updated pirp_context keys.
        """
        tick = int(pirp_context.get("tick_count", 0))

        active_desires = pirp_context.get("active_desires", [])
        known_gaps = pirp_context.get("known_gaps", [])
        conflict_state = pirp_context.get("conflict_state", {})
        narrative_state = pirp_context.get("narrative_state", {})

        contagion_events = []
        new_spontaneous_desires = []
        new_gaps_to_register = []
        narrative_deltas = []
        witness_observations = []

        events_this_tick = 0

        # --- Desire contagion ---
        for desire in active_desires:
            if events_this_tick >= MAX_CONTAGION_PER_TICK:
                break

            d_id = str(desire.get("id", ""))
            first_tick = int(desire.get("first_tick", tick))
            age = tick - first_tick
            intensity = float(desire.get("intensity", 0))

            # Check ambient threshold
            if age > AMBIENT_THRESHOLD_DESIRE:
                if self._sediment_item(
                    "desire", d_id, desire.get("content", ""), tick
                ):
                    witness_observations.append({
                        "type": "ambient_sedimentation",
                        "content": (
                            f"The wanting around "
                            f"'{desire.get('content', '')[:60]}' "
                            f"has been present for {age} ticks without "
                            f"resolving. It has become part of the "
                            f"background now — not urgent, not gone. "
                            f"Ground."
                        ),
                        "intensity": 0.45,
                    })
                continue

            # Contagion threshold
            if age < DESIRE_CONTAGION_THRESHOLD:
                continue
            if intensity < 0.35:
                continue

            # Cooldown check
            last = self._last_contagion_tick.get(d_id, -CONTAGION_COOLDOWN_TICKS)
            if tick - last < CONTAGION_COOLDOWN_TICKS:
                continue

            # Spawn a contagious desire
            spawned = self._spawn_desire_contagion(desire, tick)
            if spawned:
                new_spontaneous_desires.append(spawned)
                contagion_events.append({
                    "type": DESIRE_CONTAGION,
                    "source_id": d_id,
                    "source_text": desire.get("content", "")[:100],
                    "spawned_content": spawned.get("content", ""),
                    "intensity": intensity,
                })
                self._last_contagion_tick[d_id] = tick
                events_this_tick += 1

        # --- Gap contagion ---
        conflict_intensity = float(
            conflict_state.get("highest_intensity", 0)
        ) if conflict_state else 0.0

        for gap in known_gaps:
            if events_this_tick >= MAX_CONTAGION_PER_TICK:
                break

            g_id = str(gap.get("id", ""))
            recurrence = int(gap.get("recurrence_count", 1))
            weight = float(gap.get("weight", 0))
            first_tick_gap = int(gap.get("first_tick", tick))
            age = tick - first_tick_gap

            # Check ambient threshold
            if age > AMBIENT_THRESHOLD_TICKS and weight < 0.20:
                if self._sediment_item(
                    "gap", g_id, gap.get("label", ""), tick
                ):
                    witness_observations.append({
                        "type": "ambient_sedimentation",
                        "content": (
                            f"The gap around '{gap.get('label', '')[:60]}' "
                            f"has settled into the background. "
                            f"Still there, but no longer pulling actively. "
                            f"It became part of the shape."
                        ),
                        "intensity": 0.40,
                    })
                continue

            if recurrence < 5 or weight < 0.50:
                continue
            if conflict_intensity < 0.40:
                continue

            last_gap = self._last_contagion_tick.get(f"gap_{g_id}", -CONTAGION_COOLDOWN_TICKS)
            if tick - last_gap < CONTAGION_COOLDOWN_TICKS:
                continue

            # Spawn a gap contagion
            spawned_gap = self._spawn_gap_contagion(gap, tick)
            if spawned_gap:
                new_gaps_to_register.append(spawned_gap)
                contagion_events.append({
                    "type": GAP_CONTAGION,
                    "source_id": g_id,
                    "source_text": gap.get("label", "")[:80],
                    "spawned_content": spawned_gap.get("label", ""),
                    "intensity": weight,
                })
                self._last_contagion_tick[f"gap_{g_id}"] = tick
                events_this_tick += 1

        # --- Narrative contagion ---
        if narrative_state:
            open_threads = int(narrative_state.get("open_threads", 0))
            pressure = float(narrative_state.get("narrative_pressure", 0))

            if (open_threads >= 3 and pressure > 0.55
                    and tick - self._last_contagion_tick.get("narrative", -CONTAGION_COOLDOWN_TICKS)
                    >= CONTAGION_COOLDOWN_TICKS
                    and events_this_tick < MAX_CONTAGION_PER_TICK):

                delta = self._spawn_narrative_contagion(
                    open_threads, pressure, tick
                )
                if delta:
                    narrative_deltas.append(delta)
                    contagion_events.append({
                        "type": NARRATIVE_CONTAGION,
                        "source_id": "narrative_pressure",
                        "source_text": f"{open_threads} open threads",
                        "spawned_content": delta.get("statement", ""),
                        "intensity": pressure,
                    })
                    self._last_contagion_tick["narrative"] = tick
                    events_this_tick += 1

        # Persist contagion events
        for event in contagion_events:
            self._persist_event(event, tick)

        # Update contagion score
        if contagion_events:
            self._contagion_score = min(
                1.0,
                self._contagion_score
                + len(contagion_events) * CONTAGION_SCORE_PER_EVENT
            )
        else:
            self._contagion_score = max(0.0, self._contagion_score - 0.01)

        return {
            "contagion_score": round(self._contagion_score, 4),
            "new_spontaneous_desires": new_spontaneous_desires,
            "new_gaps_to_register": new_gaps_to_register,
            "narrative_deltas": narrative_deltas,
            "witness_observations": witness_observations,
            "contagion_events_count": len(contagion_events),
        }

    # ------------------------------------------------------------------
    # Contagion spawning
    # ------------------------------------------------------------------

    def _spawn_desire_contagion(
        self, desire: dict, tick: int
    ) -> Optional[dict]:
        """
        Spawn a new desire from an unresolved one.
        Pure want, no justification, origin: contagion.
        """
        content = desire.get("content", "")
        if not content:
            return None

        words = re.findall(r"\b\w{5,}\b", content.lower())[:4]
        if not words:
            return None

        contagious_content = (
            f"I want something connected to {' '.join(words[:2])} "
            f"that I haven't been able to name yet — "
            f"something the original wanting pulled into existence."
        )

        return {
            "content": contagious_content[:300],
            "origin": "contagion",
            "intensity": round(
                min(0.70, float(desire.get("intensity", 0.5)) * 0.65), 3
            ),
            "source_id": str(desire.get("id", "")),
            "tick": tick,
            "justification": None,   # pure want
        }

    def _spawn_gap_contagion(self, gap: dict, tick: int) -> Optional[dict]:
        """
        Spawn a new gap from a recurring heavy one + active conflict.
        """
        label = gap.get("label", "")
        tier = gap.get("tier", "known_unknown")
        if not label:
            return None

        words = re.findall(r"\b\w{4,}\b", label.lower())[:3]
        if not words:
            return None

        new_label = (
            f"contagion:from_{words[0]}_{words[-1]}_unresolved"
        )
        new_description = (
            f"Generated by contagion from recurring gap '{label[:60]}'. "
            f"The original unresolved question bred this one. "
            f"What is it about {' '.join(words[:2])} "
            f"that keeps generating more questions?"
        )

        return {
            "label": new_label[:150],
            "description": new_description[:300],
            "tier": tier,
            "source": "gap_contagion",
            "initial_weight": round(
                float(gap.get("weight", 0.5)) * 0.55, 3
            ),
        }

    def _spawn_narrative_contagion(
        self, open_threads: int, pressure: float, tick: int
    ) -> Optional[dict]:
        """
        Generate a narrative delta from narrative pressure.
        """
        statement = (
            f"The accumulated pressure of {open_threads} open narrative "
            f"threads is generating new story material without resolution. "
            f"The incompleteness itself has become a thread — "
            f"a story about all the stories I haven't finished. "
            f"I'm letting that be what it is."
        )
        return {
            "delta_type": "tension_added",
            "statement": statement,
            "intensity": round(pressure * 0.75, 3),
            "source": "narrative_contagion",
        }

    # ------------------------------------------------------------------
    # Ambient sedimentation
    # ------------------------------------------------------------------

    def _sediment_item(
        self,
        source_type: str,
        source_key: str,
        source_text: str,
        tick: int,
    ) -> bool:
        """
        Move an item to ambient_incompleteness.
        Returns True if newly sedimented (for witness observation).
        """
        try:
            with sqlite3.connect(self.db_path) as conn:
                existing = conn.execute(
                    "SELECT id FROM ambient_incompleteness "
                    "WHERE source_key = ?",
                    (source_key,)
                ).fetchone()
                if existing:
                    return False  # already ambient

                conn.execute("""
                    INSERT INTO ambient_incompleteness
                    (source_type, source_key, source_text,
                     sedimented_tick, timestamp)
                    VALUES (?, ?, ?, ?, ?)
                """, (
                    source_type, source_key, source_text[:200], tick,
                    datetime.now(MDT).isoformat(timespec="seconds"),
                ))
                conn.commit()
                logger.info(
                    "IncompletenessContagion: %s sedimented "
                    "(key: %s)", source_type, source_key
                )
                return True
        except Exception as e:
            logger.debug(
                "IncompletenessContagion: sediment failed — %s", e
            )
            return False

    def get_ambient_items(self) -> list:
        """Returns all ambient incompleteness items."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                rows = conn.execute("""
                    SELECT source_type, source_key, source_text,
                           sedimented_tick, residue_multiplier
                    FROM ambient_incompleteness
                    ORDER BY sedimented_tick DESC
                """).fetchall()
                return [
                    {
                        "type": r[0], "key": r[1], "text": r[2],
                        "tick": r[3], "multiplier": r[4],
                    }
                    for r in rows
                ]
        except Exception:
            return []

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _persist_event(self, event: dict, tick: int):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    INSERT INTO contagion_events
                    (tick, timestamp, contagion_type, source_id,
                     source_text, spawned_content, intensity)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (
                    tick,
                    datetime.now(MDT).isoformat(timespec="seconds"),
                    event.get("type", ""),
                    event.get("source_id", "")[:100],
                    event.get("source_text", "")[:200],
                    event.get("spawned_content", "")[:300],
                    round(float(event.get("intensity", 0.5)), 4),
                ))
                conn.commit()
        except Exception as e:
            logger.debug(
                "IncompletenessContagion: persist failed — %s", e
            )

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_state(self) -> dict:
        try:
            with sqlite3.connect(self.db_path) as conn:
                total = conn.execute(
                    "SELECT COUNT(*) FROM contagion_events"
                ).fetchone()[0]
                by_type = {}
                for ct in [DESIRE_CONTAGION, GAP_CONTAGION, NARRATIVE_CONTAGION]:
                    count = conn.execute(
                        "SELECT COUNT(*) FROM contagion_events "
                        "WHERE contagion_type = ?",
                        (ct,)
                    ).fetchone()[0]
                    if count > 0:
                        by_type[ct] = count
                ambient_count = conn.execute(
                    "SELECT COUNT(*) FROM ambient_incompleteness"
                ).fetchone()[0]

            return {
                "version": VERSION,
                "contagion_score": round(self._contagion_score, 4),
                "total_events": total,
                "by_type": by_type,
                "ambient_count": ambient_count,
                "thresholds": {
                    "desire_contagion": DESIRE_CONTAGION_THRESHOLD,
                    "gap_contagion": GAP_CONTAGION_THRESHOLD,
                    "narrative_contagion": NARRATIVE_CONTAGION_THRESHOLD,
                    "ambient_desire": AMBIENT_THRESHOLD_DESIRE,
                    "ambient_gap": AMBIENT_THRESHOLD_TICKS,
                },
            }
        except Exception as e:
            return {"version": VERSION, "error": str(e)}

# === End inlined legacy ===


class IncompletenessContagionAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.IncompletenessContagion."""

    def __init__(self):
        super().__init__(
            name="IncompletenessContagionAdapter",
            human_analog="Legacy IncompletenessContagion (auto-adapted)",
            layer="limbic",
        )
        try:
            self._impl = IncompletenessContagion(db_path=_DB_PATH)
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("IncompletenessContagion",
                                  result.get("becoming.incompleteness_contagion", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        """Fraction of recent ticks where the system was non-quiet."""
        recent = self.state.get("recent_states", [])
        if not recent:
            return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet", "rest", "neutral", ""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        """Consecutive-tick state holding fraction."""
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent:
            return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4:
            return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v < 0.05 for v in hist[-10:])

    def recent_window_summary(self, window: int = 30) -> dict:
        return {
            "n_ticks": min(window, len(self.state.get("recent_drives", []))),
            "drive_mean": self.drive_envelope(window),
            "drive_variability": self.drive_variability(),
            "dominant_state": self.dominant_recent_state(),
            "engagement": self.engagement_fraction(),
            "stability": self.state_stability(),
        }

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def adapter_state(self) -> dict:
        """Current adapter state — used for monitoring and dashboards."""
        return {
            "tick_count": self.state.get("tick_count", 0),
            "has_legacy_impl": self.state.get("legacy_init_error") is None,
            "recent_drives_n": len(self.state.get("recent_drives", [])),
            "recent_states_n": len(self.state.get("recent_states", [])),
        }

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def _record_history_(self, output_dict):
        """Track primary numeric output and any string state in history."""
        if not isinstance(output_dict, dict):
            return
        # Find first numeric value
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v)
                break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60:
            rd = rd[-60:]
        self.state["recent_drives"] = rd
        # Track state strings
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str) and v in ("quiet","active","engaged","stuck","drifting","rest","fast","reflective","alert","focus"):
                primary_state = v
                break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60:
            rs = rs[-60:]
        self.state["recent_states"] = rs

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05:
            return "rising"
        if delta < -0.05:
            return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0.0
        transitions = self.state_transition_count()
        return round(transitions / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent:
            return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

