"""
KnownGapsAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.knowing.known_gaps.KnownGaps

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Friston 2010, Nat Rev Neurosci 11:127, free-energy principle]
  - [Barrett 2017, How Emotions Are Made]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from brain.mechanisms.known_gaps (KnownGaps) ---
import os

VERSION = "19.0"

import logging
import re
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DB_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "brain" / "agent.db"
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass
DREAMS_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "DREAMS.md"

# Tier constants
KNOWN_UNKNOWN = "known_unknown"
SUSPICION = "suspicion"
AVOIDED = "avoided"

VALID_TIERS = {KNOWN_UNKNOWN, SUSPICION, AVOIDED}

# A gap reinforces if the same label appears this many ticks apart
RECURRENCE_WINDOW_TICKS = 20

# Decay: gap weight drops by this per tick it doesn't appear
DECAY_RATE = 0.02

# Gap is considered dormant (not surfaced to salience) below this weight
DORMANT_THRESHOLD = 0.10

# Gap is auto-closed if weight reaches zero and it hasn't fired in N ticks
AUTO_CLOSE_TICKS = 200

# How many dreams to scan for gap detection on overnight pass
DREAMS_SCAN_COUNT = 30

MDT = timezone(timedelta(hours=-6))


# ---------------------------------------------------------------------------
# KnownGaps
# ---------------------------------------------------------------------------

class KnownGaps:

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = Path(db_path) if db_path else DB_PATH
        self._initialize_table()

    def _initialize_table(self):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS known_gaps (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        label TEXT NOT NULL,
                        description TEXT,
                        tier TEXT NOT NULL,
                        weight REAL DEFAULT 0.5,
                        recurrence_count INTEGER DEFAULT 1,
                        first_seen_tick INTEGER,
                        last_seen_tick INTEGER,
                        last_seen_timestamp TEXT,
                        status TEXT DEFAULT 'active',
                        resolution_note TEXT,
                        source TEXT
                    )
                """)
                conn.execute("""
                    CREATE INDEX IF NOT EXISTS idx_gaps_status
                    ON known_gaps(status)
                """)
                conn.execute("""
                    CREATE INDEX IF NOT EXISTS idx_gaps_tier
                    ON known_gaps(tier)
                """)
                conn.commit()
        except Exception as e:
            logger.error("KnownGaps: table init failed — %s", e)

    # ------------------------------------------------------------------
    # Tick-level process — called by bootstrap each tick
    # ------------------------------------------------------------------

    def process(self, pirp_context: dict) -> dict:
        """
        BrainMechanism-compatible process() method.

        Reads pirp_context for recurring signals, detects new gaps,
        reinforces existing ones, applies decay.

        Returns dict with 'known_gaps' key for injection into pirp_context
        (consumed by SalienceFilter).
        """
        tick = int(pirp_context.get("tick_count", 0))
        signals = pirp_context.get("signals", [])

        self._detect_from_signals(signals, tick)
        self._apply_decay(tick)

        active = self.get_active_gaps()
        return {"known_gaps": active}

    # ------------------------------------------------------------------
    # Gap registration
    # ------------------------------------------------------------------

    def register(
        self,
        label: str,
        description: str,
        tier: str,
        tick: int = 0,
        source: str = "manual",
        initial_weight: float = 0.5,
    ) -> int:
        """
        Register a new gap or reinforce an existing one by label.
        Returns the gap id.
        """
        if tier not in VALID_TIERS:
            tier = KNOWN_UNKNOWN

        label = label.strip().lower()[:200]
        now = datetime.now(MDT).isoformat(timespec="seconds")

        try:
            with sqlite3.connect(self.db_path) as conn:
                row = conn.execute(
                    "SELECT id, weight, recurrence_count FROM known_gaps "
                    "WHERE label = ? AND status = 'active'",
                    (label,)
                ).fetchone()

                if row:
                    gap_id, current_weight, recurrence = row
                    new_weight = min(1.0, current_weight + 0.15)
                    conn.execute("""
                        UPDATE known_gaps
                        SET weight = ?,
                            recurrence_count = ?,
                            last_seen_tick = ?,
                            last_seen_timestamp = ?,
                            description = COALESCE(?, description)
                        WHERE id = ?
                    """, (new_weight, recurrence + 1, tick, now, description or None, gap_id))
                    logger.debug("KnownGaps: reinforced '%s' → %.2f", label, new_weight)
                    conn.commit()
                    return gap_id
                else:
                    cursor = conn.execute("""
                        INSERT INTO known_gaps
                        (label, description, tier, weight, recurrence_count,
                         first_seen_tick, last_seen_tick, last_seen_timestamp, source)
                        VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?)
                    """, (label, description, tier, initial_weight, tick, tick, now, source))
                    gap_id = cursor.lastrowid
                    logger.debug("KnownGaps: registered '%s' (tier: %s)", label, tier)
                    conn.commit()
                    return gap_id
        except Exception as e:
            logger.error("KnownGaps: register failed — %s", e)
            return -1

    def resolve(self, label: str, note: str = "") -> bool:
        """Mark a gap as resolved. Archived, not deleted."""
        label = label.strip().lower()
        try:
            with sqlite3.connect(self.db_path) as conn:
                result = conn.execute("""
                    UPDATE known_gaps
                    SET status = 'resolved', resolution_note = ?
                    WHERE label = ? AND status = 'active'
                """, (note, label))
                conn.commit()
                if result.rowcount > 0:
                    logger.info("KnownGaps: resolved '%s'", label)
                    return True
                return False
        except Exception as e:
            logger.error("KnownGaps: resolve failed — %s", e)
            return False

    # ------------------------------------------------------------------
    # Auto-detection from signals
    # ------------------------------------------------------------------

    def _detect_from_signals(self, signals: list, tick: int):
        question_markers = [
            "why", "what if", "how come", "i don't know", "unsure",
            "unclear", "uncertain", "don't understand", "confused",
            "wonder", "wondering", "still don't", "never resolved",
        ]
        suspicion_markers = [
            "i think maybe", "possibly", "might be", "could be that",
            "not sure but", "suspect", "feeling like", "sense that",
        ]
        avoidance_markers = [
            "not going to", "avoiding", "don't want to think",
            "leaving that", "skipping", "moving on from",
        ]

        for sig in signals:
            text = sig.get("text", "").lower()
            if not text:
                continue

            if any(m in text for m in question_markers):
                label = self._extract_label(text, "question")
                if label:
                    self.register(label, text[:300], KNOWN_UNKNOWN, tick, "signal_detection")

            elif any(m in text for m in suspicion_markers):
                label = self._extract_label(text, "suspicion")
                if label:
                    self.register(label, text[:300], SUSPICION, tick, "signal_detection")

            elif any(m in text for m in avoidance_markers):
                label = self._extract_label(text, "avoidance")
                if label:
                    self.register(label, text[:300], AVOIDED, tick, "signal_detection")

    def _extract_label(self, text: str, gap_type: str) -> Optional[str]:
        stopwords = {
            "why", "what", "that", "this", "the", "and", "but", "for",
            "with", "from", "have", "been", "about", "think", "know",
            "going", "want", "feel", "like", "just", "still", "maybe",
            "could", "would", "should", "dont", "doesnt", "isnt", "not",
        }
        words = re.findall(r"\b\w{4,}\b", text.lower())
        content_words = [w for w in words if w not in stopwords][:5]

        if len(content_words) < 2:
            return None

        return f"{gap_type}:{' '.join(content_words[:4])}"

    # ------------------------------------------------------------------
    # Overnight DREAMS.md scan
    # ------------------------------------------------------------------

    def scan_dreams(self, tick: int = 0):
        """
        Overnight pass: scan recent DREAMS.md entries for recurring
        unresolved questions. Registers them as known gaps.

        Call from the overnight pipeline (2am–5am block).
        """
        if not DREAMS_PATH.exists():
            return

        try:
            text = DREAMS_PATH.read_text(encoding="utf-8")
        except Exception as e:
            logger.error("KnownGaps: dreams scan read failed — %s", e)
            return

        blocks = text.split("\n---\n")
        insight_texts = []

        for block in blocks[-DREAMS_SCAN_COUNT:]:
            block = block.strip()
            if not block or "compressor_offline" in block:
                continue
            lines = block.splitlines()
            in_meta = True
            for line in lines:
                if in_meta and ": " not in line:
                    in_meta = False
                if not in_meta and line.strip():
                    insight_texts.append(line.strip())

        question_patterns = [
            r"i don't know",
            r"still.*question",
            r"keep coming back",
            r"not sure",
            r"still unresolved",
            r"can't figure",
            r"wonder",
            r"why.*still",
        ]

        for insight in insight_texts:
            lower = insight.lower()
            for pattern in question_patterns:
                if re.search(pattern, lower):
                    label = self._extract_label(lower, "dream_question")
                    if label:
                        self.register(
                            label=label,
                            description=insight[:300],
                            tier=KNOWN_UNKNOWN,
                            tick=tick,
                            source="dreams_scan",
                            initial_weight=0.4,
                        )
                        break

        logger.info("KnownGaps: dreams scan complete (%d insights scanned)", len(insight_texts))

    # ------------------------------------------------------------------
    # Decay
    # ------------------------------------------------------------------

    def _apply_decay(self, tick: int):
        """Reduce weight of gaps that weren't seen this tick. Auto-close old zeros."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    UPDATE known_gaps
                    SET weight = MAX(0.0, weight - ?)
                    WHERE status = 'active'
                    AND last_seen_tick != ?
                """, (DECAY_RATE, tick))

                conn.execute("""
                    UPDATE known_gaps
                    SET status = 'auto_closed'
                    WHERE status = 'active'
                    AND weight <= 0.0
                    AND (? - last_seen_tick) > ?
                """, (tick, AUTO_CLOSE_TICKS))

                conn.commit()
        except Exception as e:
            logger.debug("KnownGaps: decay update failed — %s", e)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_active_gaps(
        self,
        tier: Optional[str] = None,
        min_weight: float = DORMANT_THRESHOLD,
    ) -> list:
        """Returns active gaps above dormant threshold, optionally filtered by tier."""
        try:
            with sqlite3.connect(self.db_path) as conn:
                if tier:
                    rows = conn.execute("""
                        SELECT id, label, description, tier, weight,
                               recurrence_count, last_seen_tick, source
                        FROM known_gaps
                        WHERE status = 'active' AND tier = ? AND weight >= ?
                        ORDER BY weight DESC
                    """, (tier, min_weight)).fetchall()
                else:
                    rows = conn.execute("""
                        SELECT id, label, description, tier, weight,
                               recurrence_count, last_seen_tick, source
                        FROM known_gaps
                        WHERE status = 'active' AND weight >= ?
                        ORDER BY weight DESC
                    """, (min_weight,)).fetchall()

                return [
                    {
                        "id": r[0],
                        "label": r[1],
                        "description": r[2],
                        "tier": r[3],
                        "weight": r[4],
                        "recurrence_count": r[5],
                        "last_seen_tick": r[6],
                        "source": r[7],
                    }
                    for r in rows
                ]
        except Exception as e:
            logger.error("KnownGaps: get_active_gaps failed — %s", e)
            return []

    def get_heaviest(self, n: int = 3) -> list:
        """Returns the N highest-weight active gaps. Used by Inner Voice."""
        return self.get_active_gaps()[:n]

    def get_state(self) -> dict:
        try:
            with sqlite3.connect(self.db_path) as conn:
                counts = conn.execute("""
                    SELECT tier, COUNT(*), AVG(weight)
                    FROM known_gaps
                    WHERE status = 'active'
                    GROUP BY tier
                """).fetchall()
                total = conn.execute(
                    "SELECT COUNT(*) FROM known_gaps WHERE status = 'active'"
                ).fetchone()[0]
                resolved = conn.execute(
                    "SELECT COUNT(*) FROM known_gaps WHERE status = 'resolved'"
                ).fetchone()[0]

                return {
                    "version": VERSION,
                    "active_total": total,
                    "resolved_total": resolved,
                    "by_tier": {
                        r[0]: {"count": r[1], "avg_weight": round(r[2], 3)}
                        for r in counts
                    },
                }
        except Exception as e:
            logger.error("KnownGaps: get_state failed — %s", e)
            return {"version": VERSION, "error": str(e)}


class KnownGapsAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.KnownGaps."""

    def __init__(self):
        super().__init__(
            name="KnownGapsAdapter",
            human_analog="Legacy KnownGaps (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = KnownGaps(db_path=_DB_PATH)
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("KnownGaps",
                                  result.get("knowing.known_gaps", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output
