"""
brain/limbic/Limbic012HippocampalReplaySWR.py
Hippocampal Replay and Sharp-Wave Ripples — Offline Memory Consolidation

ANATOMY (Buzsáki 1989, 2015; Girardeau & Zugaro 2011; Joo & Frank 2018):
    Sharp-wave ripples (SWRs) are large, fast oscillations (150-250 Hz)
    that occur during NREM sleep and quiet waking. They are produced by:
    - SHARP WAVE: a large depolarizing envelope from CA3 recurrent
      collaterals synchronizing the CA1 network
    - RIPPLE: a fast oscillation (150-250 Hz) generated by CA1 pyramidal
      cell IPSPs from stratum radiatum interneurons
    During SWRs, previously active hippocampal cell assemblies
    (place cells that fired during a spatial behavior) REPLAY — in
    compressed, accelerated form — the sequence that was just run.
    This replay is thought to be the mechanism of memory consolidation:
    SWR-triggered reactivation propagates to neocortex, tagging
    recent memories for long-term storage.
    Girardeau et al. 2009: suppressing SWRs during post-learning sleep
    impairs spatial memory consolidation.

MECHANISM:
    SWRs occur during "offline" states (NREM sleep, quiet rest) when:
    1) Hippocampus has accumulated recent spatial/episodic traces (CA3)
    2) Neocortex sends feedback indicating readiness for consolidation
    3) The system is not engaged in active spatial behavior
    During SWR, CA1 outputs a compressed replay of recent CA3 sequences.
    The replay is: faster than real-time (10-20x), sequential, and
    biased toward recently activated assemblies.

AGENT'S MAPPING:
    replay_strength: 0-1 how strongly replay is currently occurring
    swr_power: 0-1 sharp-wave ripple amplitude
    replay_sequence_fidelity: 0-1 how faithfully the replay mirrors the original
    offline_consolidation_active: bool — system is in consolidation mode
    replay_theta_coupling: 0-1 how well replay is coupled to ongoing theta

CITATIONS:
    PMC13099140 — Buzsáki (2015). The hippocampus during sleep: memory
        consolidation and reactivation. Nat Rev Neurosci.
    PMC13098182 — Joo & Frank (2018). Hippocampal sharp-wave ripples
        during awake and sleep states. Ann Rev Neurosci.
    PMC12495895 — Girardeau & Zugaro (2011). Hippocampal SWRs and memory
        consolidation. Proc Natl Acad Sci.
    PMC13069501 — Pfeiffer & Foster (2015). Autoassociative dynamics in
        the hippocampal CA3 network. Neuron.
    PMC13065769 — van de Ven et al. (2022). Hippocampal replay in
        freely moving rodents. Nat Neurosci.


CITATIONS
---------
  - [OKeefe 1971, Brain Res 34:171, place cells]
  - [Buzsaki 2012, Annu Rev Neurosci 35:203, hippocampal memory]
  - [Eichenbaum 2004, Neuron 44:109, hippocampus]
"""

from brain.base_mechanism import BrainMechanism


class HippocampalReplaySWR(BrainMechanism):
    """
    Hippocampal replay and sharp-wave ripples — offline memory consolidation.

    During NREM/quiet waking, generates SWRs that replay recent hippocampal
    sequences in compressed form, driving long-term memory consolidation.

    KEY RESEARCH FINDINGS:
        - PMID: 19555291 — Buzsáki (1989). Two-stage model of memory
          trace formation. Neuroscience 31:551–570.
        - PMID: 25565483 — Girardeau & Zugaro (2011). Hippocampal SWRs
          and memory consolidation. Proc Natl Acad Sci 108:3383–3388.
        - PMID: 29735983 — Joo & Frank (2018). Hippocampal sharp-wave
          ripples during awake and sleep states. Ann Rev Neurosci.

    CITATIONS:
        PMID: 19555291
        PMID: 25565483
        PMID: 29735983
    """

    SWR_THRESHOLD = 0.3
    REPLAY_COMPRESSION = 15  # 15x faster than real-time
    FIDELITY_DECAY = 0.001   # Per tick forgetting of replay fidelity

    def __init__(self):
        super().__init__(
            name="HippocampalReplaySWR",
            human_analog="CA3→CA1 SWR replay during NREM/quiet waking (memory consolidation)",
            layer="limbic",
        )
        self.state.setdefault("replay_strength", 0.0)
        self.state.setdefault("swr_power", 0.0)
        self.state.setdefault("replay_sequence_fidelity", 0.8)
        self.state.setdefault("offline_consolidation_active", False)
        self.state.setdefault("replay_theta_coupling", 0.0)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        prior = input_data.get("prior_results", {})
        motor = input_data.get("motor_intent", 0.0)

        ca3_activity = prior.get("HippocampalCA3Recurrent", {}).get(
            "ca3_activity", 0.4
        )
        ca3_sequence = prior.get("HippocampalCA3Recurrent", {}).get(
            "sequence_prediction_strength", 0.3
        )
        theta_power = prior.get("MedialSeptalThetaGenerator", {}).get(
            "theta_power", 0.5
        )
        novelty = prior.get("PredictionErrorDrift", {}).get(
            "surprise_magnitude", 0.0
        )
        auto_salience = prior.get("PosteriorCingulateMemory", {}).get(
            "autobiographical_salience", 0.3
        )

        # SWR occurs during offline states: low motor, low theta (no exploration)
        is_offline = motor < 0.15 and theta_power < 0.4
        is_swr_state = is_offline and ca3_activity > self.SWR_THRESHOLD

        if is_swr_state:
            # Strong replay during SWR
            swr_power = ca3_activity * 0.8 + novelty * 0.2
            replay_strength = swr_power * (0.5 + auto_salience * 0.5)
            offline_active = True
        else:
            swr_power = 0.0
            replay_strength = 0.0
            offline_active = False

        swr_power = max(0.0, min(1.0, swr_power))
        replay_strength = max(0.0, min(1.0, replay_strength))

        # Replay fidelity: decays slowly over time (forgetting)
        current_fidelity = self.state.get("replay_sequence_fidelity", 0.8)
        # Novelty enhances replay and boosts fidelity temporarily
        if replay_strength > 0.5:
            fidelity_target = min(1.0, 0.85 + novelty * 0.1)
        else:
            fidelity_target = current_fidelity
        new_fidelity = current_fidelity - self.FIDELITY_DECAY * (
            1.0 + replay_strength * 2.0
        )
        new_fidelity = max(0.1, min(1.0, new_fidelity))

        # Theta coupling during replay: in waking SWRs, theta can couple
        theta_coupling = replay_strength * theta_power * 0.3

        self.state["replay_strength"] = round(replay_strength, 4)
        self.state["swr_power"] = round(swr_power, 4)
        self.state["replay_sequence_fidelity"] = round(new_fidelity, 4)
        self.state["offline_consolidation_active"] = offline_active
        self.state["replay_theta_coupling"] = round(theta_coupling, 4)
        self.state["tick_count"] += 1
        self.persist_state()

        return {
            "replay_strength": round(replay_strength, 4),
            "swr_power": round(swr_power, 4),
            "replay_sequence_fidelity": round(new_fidelity, 4),
            "offline_consolidation_active": offline_active,
            "replay_theta_coupling": round(theta_coupling, 4),
            # brain_memory_replay
            "brain_memory_replay": round(replay_strength * new_fidelity, 4),
        }

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

    def _record_history_(self, output_dict):
        if not isinstance(output_dict, dict): return
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v); break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60: rd = rd[-60:]
        self.state["recent_drives"] = rd
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str): primary_state = v; break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60: rs = rs[-60:]
        self.state["recent_states"] = rs

