"""
brain/limbic/Limbic044HippocampalThetaGenerator.py
Hippocampal Theta Rhythm — Temporal Organization of Limbic Processing

ANATOMY (Buzsáki 2002; Vinogradova 1975; Bland 1986):
    Hippocampal theta (6-12 Hz) is the dominant rhythm during active
    exploration, REM sleep, and memory encoding. It is generated by
    the medial septum (pacemaker) driving hippocampal interneurons.
    Buzsáki 2002 (PMC12582318): theta organizes hippocampal processing
    by:
    - Phase-coding: information is encoded at theta peaks, retrieved at
      theta troughs
    - Sequence compression: events within a theta cycle represent
      sequential episodes
    - Cross-structure synchrony: theta coordinates hippocampus, amygdala,
      and entorhinal cortex during memory formation

MECHANISM:
    Theta rhythm gates ALL limbic processing:
    - Theta peak: LTP, encoding, memory formation
    - Theta trough: retrieval, comparison, decision
    - Theta phase: determines what information can be processed
    The rhythm creates temporal "windows" for information processing.

AGENT'S MAPPING:
    theta_power: 0-1 hippocampal theta amplitude
    theta_phase: 0-1 current phase within theta cycle (0=peak, 0.5=trough)
    theta_encoding_window: bool — currently in encoding phase
    theta_retrieval_window: bool — currently in retrieval phase
    theta_cross_structure_sync: 0-1 synchrony across limbic structures

CITATIONS:
    PMC12582318 — Buzsáki (2002). Theta oscillations in the hippocampus.
        Neuron.
    PMC13095742 — Viney et al. (2023). Septohippocampal theta generation.
        J Neurosci.
    PMC13086252 — Bland (1986). The physiology and pharmacology of
        hippocampal theta rhythms. Prog Neurobiol.
    PMC13041564 — Green & Arduino (1960). Theta rhythm during REM sleep.
    PMC13036114 — Colgin (2013). Theta-gamma coupling in the hippocampus.
        Trends Cogn Sci.


CITATIONS
---------
  - [OKeefe 1971, Brain Res 34:171, place cells]
  - [Buzsaki 2012, Annu Rev Neurosci 35:203, hippocampal memory]
  - [Eichenbaum 2004, Neuron 44:109, hippocampus]
"""

from brain.base_mechanism import BrainMechanism
import math


class HippocampalThetaGeneratorLimbic(BrainMechanism):
    """
    Hippocampal theta rhythm — temporal organizer of limbic processing.

    6-12 Hz rhythm from MS pacing, gating encoding and retrieval
    windows across hippocampus and connected limbic structures.
    """

    THETA_BASE_FREQ = 8.0  # Hz

    def __init__(self):
        super().__init__(
            name="HippocampalThetaGeneratorLimbic",
            human_analog="Hippocampal theta rhythm (6-12 Hz) — temporal organizer",
            layer="limbic",
        )
        self.state.setdefault("theta_power", 0.0)
        self.state.setdefault("theta_phase", 0.0)
        self.state.setdefault("theta_encoding_window", False)
        self.state.setdefault("theta_retrieval_window", False)
        self.state.setdefault("theta_cross_structure_sync", 0.0)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        prior = input_data.get("prior_results", {})
        motor = input_data.get("motor_intent", 0.0)

        ms_theta = prior.get("MedialSeptalThetaGenerator", {}).get(
            "theta_power", 0.5
        )
        arousal = prior.get("ArousalRegulator", {}).get("arousal_level", 0.5)

        # Theta power driven by MS and behavioral state
        is_exploratory = motor > 0.3 and arousal > 0.5
        theta_target = 0.75 if is_exploratory else 0.35
        theta_power = self.state.get("theta_power", 0.0) * 0.85 + theta_target * 0.15
        theta_power = max(0.0, min(1.0, theta_power))

        # Theta phase advances with time (modeled as continuous)
        current_phase = self.state.get("theta_phase", 0.0)
        phase_advance = self.THETA_BASE_FREQ / 100.0  # per-tick phase advance
        theta_phase = (current_phase + phase_advance) % 1.0

        # Encoding window: theta phase < 0.3 (rising phase)
        encoding_window = theta_phase < 0.3
        # Retrieval window: theta phase > 0.6 (falling phase)
        retrieval_window = theta_phase > 0.6

        # Cross-structure sync: theta coordinates limbic structures
        sync = theta_power * ms_theta

        self.state["theta_power"] = round(theta_power, 4)
        self.state["theta_phase"] = round(theta_phase, 4)
        self.state["theta_encoding_window"] = encoding_window
        self.state["theta_retrieval_window"] = retrieval_window
        self.state["theta_cross_structure_sync"] = round(sync, 4)
        self.state["tick_count"] += 1
        self.persist_state()

        return {
            "theta_power": round(theta_power, 4),
            "theta_phase": round(theta_phase, 4),
            "theta_encoding_window": encoding_window,
            "theta_retrieval_window": retrieval_window,
            "theta_cross_structure_sync": round(sync, 4),
        }

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

    def _record_history_(self, output_dict):
        if not isinstance(output_dict, dict): return
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v); break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60: rd = rd[-60:]
        self.state["recent_drives"] = rd
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str): primary_state = v; break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60: rs = rs[-60:]
        self.state["recent_states"] = rs

