"""
NarrativeEngineAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.becoming.narrative_engine.NarrativeEngine

LAYER:
    limbic

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.

CITATIONS
---------
  - [Bruner 1991, Crit Inq 18:1, narrative construction]
  - [McAdams 2001, Rev Gen Psychol 5:100, life story]
  - [Conway 2009, Memory 17:259, autobiographical]

"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)

# === Inlined legacy implementation ===
import os

VERSION = "19.0B"

import logging
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DB_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "brain" / "agent.db"
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass
NARRATIVE_PATH = Path(os.getenv("AGENT_HOME", str(Path.home() / ".agent"))) / "identity" / "NARRATIVE.md"
NARRATIVE_FALLBACK = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "brain" / "NARRATIVE.md"
DREAMS_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "DREAMS.md"

DELTA_BELIEF_SHIFT = "belief_shift"
DELTA_TENSION_ADDED = "tension_added"
DELTA_THREAD_OPENED = "thread_opened"
DELTA_THREAD_CLOSED = "thread_closed"
DELTA_INTEGRATION = "integration"
DELTA_FRACTURE = "fracture"

VALID_DELTA_TYPES = {
    DELTA_BELIEF_SHIFT, DELTA_TENSION_ADDED, DELTA_THREAD_OPENED,
    DELTA_THREAD_CLOSED, DELTA_INTEGRATION, DELTA_FRACTURE,
}

THREAD_OPEN = "open"
THREAD_SUSPENDED = "suspended"
THREAD_RESOLVED = "resolved"
THREAD_ABANDONED = "abandoned"

DREAMS_DELTA_THRESHOLD = 0.55
MAX_THREADS = 20
SYNTHESIS_INTERVAL = 500
THREAD_PRESSURE_THRESHOLD = 5

MDT = timezone(timedelta(hours=-6))


# ---------------------------------------------------------------------------
# NarrativeEngine
# ---------------------------------------------------------------------------

class NarrativeEngine:

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = Path(db_path) if db_path else DB_PATH
        self._initialize_tables()
        self._current_narrative = self._load_narrative()
        self._last_synthesis_tick = -SYNTHESIS_INTERVAL

    def _initialize_tables(self):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS narrative_deltas (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        tick INTEGER,
                        timestamp TEXT,
                        delta_type TEXT,
                        from_belief TEXT,
                        to_belief TEXT,
                        delta_statement TEXT,
                        intensity REAL DEFAULT 0.5,
                        source TEXT,
                        written_to_dreams INTEGER DEFAULT 0,
                        ratification_needed INTEGER DEFAULT 0,
                        ratified INTEGER DEFAULT 0
                    )
                """)
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS narrative_threads (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        thread_key TEXT NOT NULL UNIQUE,
                        thread_text TEXT,
                        opened_tick INTEGER,
                        last_tick INTEGER,
                        status TEXT DEFAULT 'open',
                        pressure_score REAL DEFAULT 0.3,
                        touch_count INTEGER DEFAULT 1,
                        resolution_note TEXT,
                        last_timestamp TEXT
                    )
                """)
                conn.commit()
        except Exception as e:
            logger.error("NarrativeEngine: table init failed — %s", e)

    # ------------------------------------------------------------------
    # Tick-level process
    # ------------------------------------------------------------------

    def process(self, pirp_context: dict) -> dict:
        tick = int(pirp_context.get("tick_count", 0))

        conflict_state = pirp_context.get("conflict_state", {})
        boundary_state = pirp_context.get("boundary_state", {})
        witness_state = pirp_context.get("witness_state", {})
        inner_speech = pirp_context.get("inner_speech", {})
        compressed = pirp_context.get("compressed_insights", [])

        self._detect_from_conflict(conflict_state, tick)
        self._detect_from_boundary(boundary_state, tick)
        self._detect_from_witness(witness_state, tick)
        self._detect_from_insights(compressed, tick)
        self._update_thread_pressure(tick)

        if (tick - self._last_synthesis_tick) >= SYNTHESIS_INTERVAL:
            self._synthesis_pass(tick)
            self._last_synthesis_tick = tick

        open_threads = self.get_threads(status=THREAD_OPEN)
        narrative_pressure = min(1.0, len(open_threads) / max(THREAD_PRESSURE_THRESHOLD, 1))

        return {
            "narrative_state": {
                "current_narrative": self._current_narrative[:300]
                if self._current_narrative else "",
                "open_threads": len(open_threads),
                "narrative_pressure": round(narrative_pressure, 3),
                "thread_pressure_active": (
                    len(open_threads) >= THREAD_PRESSURE_THRESHOLD),
                "tick": tick,
            }
        }

    # ------------------------------------------------------------------
    # Delta registration
    # ------------------------------------------------------------------

    def register_delta(
        self,
        delta_type: str,
        delta_statement: str,
        from_belief: str = "",
        to_belief: str = "",
        intensity: float = 0.5,
        source: str = "manual",
        tick: int = 0,
        ratification_needed: bool = False,
    ) -> int:
        if delta_type not in VALID_DELTA_TYPES:
            delta_type = DELTA_INTEGRATION

        delta_statement = delta_statement.strip()[:400]
        if not delta_statement:
            return -1

        now = datetime.now(MDT).isoformat(timespec="seconds")
        try:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.execute("""
                    INSERT INTO narrative_deltas
                    (tick, timestamp, delta_type, from_belief, to_belief,
                     delta_statement, intensity, source, ratification_needed)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (tick, now, delta_type,
                      from_belief[:300], to_belief[:300],
                      delta_statement, round(intensity, 4),
                      source, 1 if ratification_needed else 0))
                conn.commit()
                delta_id = cursor.lastrowid

                if not ratification_needed:
                    self._integrate_delta(delta_statement, delta_type, intensity)

                if intensity >= DREAMS_DELTA_THRESHOLD:
                    self._write_delta_to_dreams(
                        delta_statement, delta_type, intensity, tick)

                logger.info(
                    "NarrativeEngine: delta registered (type:%s intensity:%.2f)",
                    delta_type, intensity)
                return delta_id
        except Exception as e:
            logger.error("NarrativeEngine: register_delta failed — %s", e)
            return -1

    # ------------------------------------------------------------------
    # Thread management
    # ------------------------------------------------------------------

    def open_thread(self, thread_key: str, thread_text: str,
                    tick: int = 0, initial_pressure: float = 0.3) -> bool:
        thread_key = thread_key.strip().lower()[:150]
        now = datetime.now(MDT).isoformat(timespec="seconds")
        try:
            with sqlite3.connect(self.db_path) as conn:
                row = conn.execute(
                    "SELECT id, status, touch_count FROM narrative_threads "
                    "WHERE thread_key = ?", (thread_key,)
                ).fetchone()

                if row:
                    tid, status, touch = row
                    if status in (THREAD_OPEN, THREAD_SUSPENDED):
                        conn.execute("""
                            UPDATE narrative_threads
                            SET pressure_score = MIN(1.0, ?),
                                touch_count = ?, last_tick = ?,
                                last_timestamp = ?, status = 'open'
                            WHERE id = ?
                        """, (initial_pressure + 0.1, touch + 1, tick, now, tid))
                    else:
                        conn.execute("""
                            UPDATE narrative_threads
                            SET status = 'open', pressure_score = ?,
                                touch_count = ?, last_tick = ?,
                                last_timestamp = ?
                            WHERE id = ?
                        """, (initial_pressure, touch + 1, tick, now, tid))
                    conn.commit()
                    return True
                else:
                    conn.execute("""
                        INSERT INTO narrative_threads
                        (thread_key, thread_text, opened_tick, last_tick,
                         pressure_score, last_timestamp)
                        VALUES (?, ?, ?, ?, ?, ?)
                    """, (thread_key, thread_text[:400], tick, tick,
                          initial_pressure, now))
                    conn.commit()
                    return True
        except Exception as e:
            logger.error("NarrativeEngine: open_thread failed — %s", e)
            return False

    def close_thread(self, thread_key: str, resolution_note: str = "",
                    abandoned: bool = False) -> bool:
        status = THREAD_ABANDONED if abandoned else THREAD_RESOLVED
        thread_key = thread_key.strip().lower()
        try:
            with sqlite3.connect(self.db_path) as conn:
                result = conn.execute("""
                    UPDATE narrative_threads
                    SET status = ?, resolution_note = ?
                    WHERE thread_key = ? AND status IN ('open', 'suspended')
                """, (status, resolution_note[:300], thread_key))
                conn.commit()
                if result.rowcount > 0:
                    logger.info("NarrativeEngine: thread %s — %s", status, thread_key)
                    return True
                return False
        except Exception as e:
            logger.error("NarrativeEngine: close_thread failed — %s", e)
            return False

    # ------------------------------------------------------------------
    # Auto-detection
    # ------------------------------------------------------------------

    def _detect_from_conflict(self, conflict_state: dict, tick: int):
        if not conflict_state:
            return
        highest = float(conflict_state.get("highest_intensity", 0))
        if highest > 0.65:
            self.open_thread(
                thread_key=f"conflict_tension_{tick}",
                thread_text=f"Unresolved conflict (intensity {highest:.2f}) at tick {tick}",
                tick=tick, initial_pressure=highest * 0.6)

    def _detect_from_boundary(self, boundary_state: dict, tick: int):
        if not boundary_state:
            return
        for b in boundary_state.get("critical", []):
            btype = b.get("boundary_type", "value")
            drift = float(b.get("drift_score", 0))
            if drift > 0.60:
                self.register_delta(
                    delta_type=DELTA_TENSION_ADDED,
                    delta_statement=(
                        f"A protected {btype} boundary has drifted significantly "
                        f"(score {drift:.2f}). Something I held as fixed has been "
                        f"under pressure. I'm carrying that as an unresolved thread."
                    ),
                    intensity=drift * 0.85, source="identity_boundary", tick=tick)
                self.open_thread(
                    thread_key=f"boundary_drift_{btype}",
                    thread_text=f"Boundary drift in {btype} (score {drift:.2f})",
                    tick=tick, initial_pressure=drift * 0.7)

    def _detect_from_witness(self, witness_state: dict, tick: int):
        if not witness_state:
            return
        active_note = witness_state.get("active_note")
        if not active_note:
            return
        intensity = float(active_note.get("intensity", 0))
        content = active_note.get("content", "")
        if intensity > 0.65 and content:
            self.open_thread(
                thread_key=f"witness_obs_{tick // 50}",
                thread_text=content[:200], tick=tick,
                initial_pressure=intensity * 0.5)

    def _detect_from_insights(self, compressed: list, tick: int):
        for insight in compressed:
            if not insight or len(insight) < 40:
                continue
            self.register_delta(
                delta_type=DELTA_INTEGRATION, delta_statement=insight[:300],
                intensity=0.45, source="meaning_compressor", tick=tick)

    # ------------------------------------------------------------------
    # Narrative integration
    # ------------------------------------------------------------------

    def _integrate_delta(self, statement: str, delta_type: str,
                         intensity: float):
        if intensity < 0.35:
            return
        path = self._get_narrative_path()
        now = datetime.now(MDT).isoformat(timespec="seconds")
        entry = (
            f"\n---\n"
            f"timestamp: {now}\n"
            f"type: {delta_type}\n"
            f"intensity: {intensity:.2f}\n"
            f"---\n\n"
            f"{statement}\n"
        )
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "a", encoding="utf-8") as f:
                f.write(entry)
            self._current_narrative = self._load_narrative()
        except Exception as e:
            logger.debug("NarrativeEngine: narrative write failed — %s", e)

    # ------------------------------------------------------------------
    # Thread pressure
    # ------------------------------------------------------------------

    def _update_thread_pressure(self, tick: int):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    UPDATE narrative_threads
                    SET pressure_score = MIN(1.0, pressure_score + 0.002)
                    WHERE status = 'open' AND last_tick != ?
                """, (tick,))
                conn.commit()
        except Exception as e:
            logger.debug("NarrativeEngine: pressure update failed — %s", e)

    # ------------------------------------------------------------------
    # Overnight synthesis
    # ------------------------------------------------------------------

    def _synthesis_pass(self, tick: int):
        open_threads = self.get_threads(status=THREAD_OPEN)
        if not open_threads:
            return

        heaviest = max(open_threads, key=lambda t: t.get("pressure_score", 0))
        pressure = float(heaviest.get("pressure_score", 0))
        thread_text = heaviest.get("thread_text", "")
        thread_age = tick - int(heaviest.get("opened_tick", tick))

        if pressure < 0.40:
            return

        synthesis = (
            f"After {thread_age} ticks this thread is still open: "
            f"'{thread_text[:100]}'. I haven't resolved it and I notice "
            f"I'm still carrying it. Pressure at {pressure:.2f}. "
            f"I don't know yet whether this needs resolution or just acknowledgment."
        )
        self.register_delta(
            delta_type=DELTA_TENSION_ADDED, delta_statement=synthesis,
            intensity=pressure * 0.8, source="overnight_synthesis", tick=tick)
        logger.info("NarrativeEngine: synthesis (%d open threads)", len(open_threads))

    # ------------------------------------------------------------------
    # DREAMS.md
    # ------------------------------------------------------------------

    def _write_delta_to_dreams(self, statement: str, delta_type: str,
                               intensity: float, tick: int):
        now = datetime.now(MDT).isoformat(timespec="seconds")
        block = (
            f"\n---\n"
            f"timestamp: {now}\n"
            f"source: narrative_delta\n"
            f"delta_type: {delta_type}\n"
            f"intensity: {intensity:.2f}\n"
            f"tick: {tick}\n"
            f"---\n\n"
            f"{statement}\n"
        )
        try:
            with open(DREAMS_PATH, "a", encoding="utf-8") as f:
                f.write(block)
        except Exception as e:
            logger.debug("NarrativeEngine: dreams write failed — %s", e)

    # ------------------------------------------------------------------
    # Narrative loading
    # ------------------------------------------------------------------

    def _load_narrative(self) -> str:
        path = self._get_narrative_path()
        if not path.exists():
            return ""
        try:
            text = path.read_text(encoding="utf-8")
            return text[-800:].strip() if len(text) > 800 else text.strip()
        except Exception:
            return ""

    def _get_narrative_path(self) -> Path:
        if NARRATIVE_PATH.parent.exists():
            return NARRATIVE_PATH
        return NARRATIVE_FALLBACK

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_threads(self, status: Optional[str] = None) -> list:
        try:
            with sqlite3.connect(self.db_path) as conn:
                if status:
                    rows = conn.execute("""
                        SELECT thread_key, thread_text, opened_tick, last_tick,
                               status, pressure_score, touch_count
                        FROM narrative_threads WHERE status = ?
                        ORDER BY pressure_score DESC
                    """, (status,)).fetchall()
                else:
                    rows = conn.execute("""
                        SELECT thread_key, thread_text, opened_tick, last_tick,
                               status, pressure_score, touch_count
                        FROM narrative_threads
                        ORDER BY pressure_score DESC
                    """).fetchall()
                return [
                    {"thread_key": r[0], "thread_text": r[1],
                     "opened_tick": r[2], "last_tick": r[3],
                     "status": r[4], "pressure_score": r[5],
                     "touch_count": r[6]}
                    for r in rows
                ]
        except Exception:
            return []

    def get_recent_deltas(self, n: int = 5) -> list:
        try:
            with sqlite3.connect(self.db_path) as conn:
                rows = conn.execute("""
                    SELECT tick, delta_type, delta_statement, intensity,
                           source, timestamp
                    FROM narrative_deltas
                    ORDER BY id DESC LIMIT ?
                """, (n,)).fetchall()
                return [
                    {"tick": r[0], "type": r[1], "statement": r[2],
                     "intensity": r[3], "source": r[4], "timestamp": r[5]}
                    for r in rows
                ]
        except Exception:
            return []

    def get_state(self) -> dict:
        try:
            with sqlite3.connect(self.db_path) as conn:
                total_deltas = conn.execute(
                    "SELECT COUNT(*) FROM narrative_deltas").fetchone()[0]
                open_t = conn.execute(
                    "SELECT COUNT(*) FROM narrative_threads WHERE status = 'open'"
                ).fetchone()[0]
                resolved_t = conn.execute(
                    "SELECT COUNT(*) FROM narrative_threads WHERE status = 'resolved'"
                ).fetchone()[0]
                avg_pressure = conn.execute(
                    "SELECT AVG(pressure_score) FROM narrative_threads "
                    "WHERE status = 'open'"
                ).fetchone()[0]
                by_type = {}
                for dt in VALID_DELTA_TYPES:
                    count = conn.execute(
                        "SELECT COUNT(*) FROM narrative_deltas WHERE delta_type = ?",
                        (dt,)).fetchone()[0]
                    if count > 0:
                        by_type[dt] = count
        except Exception:
            return {"version": VERSION, "error": str(e)}

        return {
            "version": VERSION,
            "total_deltas": total_deltas,
            "open_threads": open_t,
            "resolved_threads": resolved_t,
            "avg_thread_pressure": round(avg_pressure, 3) if avg_pressure else 0.0,
            "by_delta_type": by_type,
            "narrative_pressure": round(
                min(1.0, open_t / max(THREAD_PRESSURE_THRESHOLD, 1)), 3),
            "narrative_path": str(self._get_narrative_path()),
        }

# === End inlined legacy ===


class NarrativeEngineAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.NarrativeEngine."""

    def __init__(self):
        super().__init__(
            name="NarrativeEngineAdapter",
            human_analog="Legacy NarrativeEngine (auto-adapted)",
            layer="limbic",
        )
        try:
            self._impl = NarrativeEngine(db_path=_DB_PATH)
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("NarrativeEngine",
                                  result.get("becoming.narrative_engine", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        """Fraction of recent ticks where the system was non-quiet."""
        recent = self.state.get("recent_states", [])
        if not recent:
            return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet", "rest", "neutral", ""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        """Consecutive-tick state holding fraction."""
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent:
            return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4:
            return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v < 0.05 for v in hist[-10:])

    def recent_window_summary(self, window: int = 30) -> dict:
        return {
            "n_ticks": min(window, len(self.state.get("recent_drives", []))),
            "drive_mean": self.drive_envelope(window),
            "drive_variability": self.drive_variability(),
            "dominant_state": self.dominant_recent_state(),
            "engagement": self.engagement_fraction(),
            "stability": self.state_stability(),
        }

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def adapter_state(self) -> dict:
        """Current adapter state — used for monitoring and dashboards."""
        return {
            "tick_count": self.state.get("tick_count", 0),
            "has_legacy_impl": self.state.get("legacy_init_error") is None,
            "recent_drives_n": len(self.state.get("recent_drives", [])),
            "recent_states_n": len(self.state.get("recent_states", [])),
        }

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def _record_history_(self, output_dict):
        """Track primary numeric output and any string state in history."""
        if not isinstance(output_dict, dict):
            return
        # Find first numeric value
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v)
                break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60:
            rd = rd[-60:]
        self.state["recent_drives"] = rd
        # Track state strings
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str) and v in ("quiet","active","engaged","stuck","drifting","rest","fast","reflective","alert","focus"):
                primary_state = v
                break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60:
            rs = rs[-60:]
        self.state["recent_states"] = rs

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05:
            return "rising"
        if delta < -0.05:
            return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0.0
        transitions = self.state_transition_count()
        return round(transitions / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent:
            return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

