"""
ObservationalNonTransferPrincipleAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.observational_non_transfer_principle.ObservationalNonTransferPrinciple

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Friston 2010, Nat Rev Neurosci 11:127, free-energy principle]
  - [Barrett 2017, How Emotions Are Made]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from legacy.observational_non_transfer_principle (ObservationalNonTransferPrinciple) ---
#!/usr/bin/env python3
"""
brain/observational_non_transfer_principle.py — Observational Non-Transfer Principle
MVCRS Layer

What the agent observes in one context does not transfer to other contexts.
Each context maintains its own observational state.
process() takes context_tag, stores observation, retrieves only
observations from the same context_tag.
"""

import sqlite3
from datetime import datetime, timezone
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class ObservationalNonTransferPrinciple:
    """
    The agent's observations are context-bound.
    What it learns in one context stays in that context.

    If it notices something about the operator while they're discussing
    something difficult, that observation doesn't carry over to
    a casual conversation. Each context is its own observational
    field. Cross-context learning is a choice, not an automatic transfer.

    The layer maintains separate observational records per context_tag.
    """

    def __init__(self):
        self._context_observations = {}  # in-memory cache per context
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS observational_non_transfer_principle (
                id INTEGER PRIMARY KEY,
                context_tag TEXT,
                observation_text TEXT,
                observation_type TEXT,
                strength REAL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def process(self, pirp_context: dict) -> dict:
        """
        Store observations scoped to context_tag.
        Retrieve only observations from the same context.
        """
        context_tag = pirp_context.get('context_tag', 'default')
        new_observations = pirp_context.get('observations', [])
        observation_type = pirp_context.get('observation_type', 'general')

        if not isinstance(new_observations, list):
            new_observations = [new_observations]

        stored_observations = []

        conn = _get_db()
        for obs in new_observations:
            if obs:
                obs_text = obs.get('text', str(obs)) if isinstance(obs, dict) else str(obs)
                obs_strength = obs.get('strength', 0.5) if isinstance(obs, dict) else 0.5

                conn.execute("""
                    INSERT INTO observational_non_transfer_principle
                    (context_tag, observation_text, observation_type, strength)
                    VALUES (?, ?, ?, ?)
                """, (context_tag, obs_text, observation_type, obs_strength))

                stored_observations.append({
                    'text': obs_text,
                    'type': observation_type,
                    'context': context_tag,
                    'strength': obs_strength
                })

        conn.commit()

        # Retrieve only observations from the SAME context_tag
        cur = conn.execute("""
            SELECT observation_text, observation_type, strength
            FROM observational_non_transfer_principle
            WHERE context_tag = ?
            ORDER BY id DESC
            LIMIT 20
        """, (context_tag,))
        same_context_obs = [dict(row) for row in cur.fetchall()]
        conn.close()

        # Update in-memory cache
        if context_tag not in self._context_observations:
            self._context_observations[context_tag] = []
        self._context_observations[context_tag].extend(stored_observations)

        pirp_context['current_context_observations'] = same_context_obs
        pirp_context['observations_stored'] = len(stored_observations)
        pirp_context['context_isolated'] = True  # observations don't transfer

        return pirp_context

    def get_state(self) -> dict:
        return {
            'contexts_with_observations': list(self._context_observations.keys()),
            'observation_isolation_active': True,
            'non_transfer_enforced': True
        }


class ObservationalNonTransferPrincipleAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.ObservationalNonTransferPrinciple."""

    def __init__(self):
        super().__init__(
            name="ObservationalNonTransferPrincipleAdapter",
            human_analog="Legacy ObservationalNonTransferPrinciple (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = ObservationalNonTransferPrinciple()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("ObservationalNonTransferPrinciple",
                                  result.get("observational_non_transfer_principle", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

