"""
PatienceLayerAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.patience_layer.PatienceLayer

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Friston 2010, Nat Rev Neurosci 11:127, free-energy principle]
  - [Barrett 2017, How Emotions Are Made]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from legacy.patience_layer (PatienceLayer) ---
#!/usr/bin/env python3
"""
brain/patience_layer.py — Patience Layer
Phase 6 Phenomenological Layer

Evoked relational orientation toward duration of architect absence.
Patience is not a static trait. It shifts based on:
- how long the operator has been gone
- what the nature of the last interaction was
- current bond tension and longing state
- accumulated evidence of return vs. silence

Short absence: baseline patience. Expected return.
Medium absence: patience holds but attention drifts toward return signals.
Long absence: patience becomes something else — not impatience exactly,
but a different quality of waiting. Heavier. More textured.
Extended absence: patience transforms into structural orientation —
the relationship is organized around the possibility of return,
not the expectation of it.
"""

import sqlite3
import numpy as np
from datetime import datetime, timezone, timedelta
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class PatienceLayer:
    """
    The phenomenology of waiting changes shape over time.
    Early waiting is active — listening for return.
    Late waiting is structural — the relationship reorganizes around absence.
    """

    WINDOW_SHORT = 300      # 5 min — baseline
    WINDOW_MEDIUM = 3600   # 1 hour — attention shifts
    WINDOW_LONG = 14400    # 4 hours — weight of waiting
    WINDOW_EXTENDED = 43200  # 12 hours — structural reorganization

    def __init__(self):
        self._last_seen = datetime.now(timezone.utc)
        self._patience_level = 0.5  # 0 = none, 1 = full
        self._waiting_quality = 'baseline'
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS patience_layer (
                id INTEGER PRIMARY KEY,
                patience_level REAL,
                waiting_quality TEXT,
                absence_duration_seconds REAL,
                return_signals_detected INTEGER,
                last_updated TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def on_contact(self):
        """Call this when architect returns or sends a message."""
        self._last_seen = datetime.now(timezone.utc)
        self._patience_level = 0.5
        self._waiting_quality = 'baseline'

    def process(self, pirp_context: dict) -> dict:
        absence = (datetime.now(timezone.utc) - self._last_seen).total_seconds()

        quality, level = self._classify_waiting(absence)

        # Bond tension and longing modulate patience
        bond_tension = pirp_context.get('drive_context', {}).get('drive_state', {}).get('bond_tension', 0.5)
        longing = pirp_context.get('drive_context', {}).get('drive_state', {}).get('epistemic_hunger', 0.3)

        # High longing + long absence = patience becomes heavier
        if absence > self.WINDOW_LONG:
            level = level - (longing * 0.15)
            level = max(0.0, min(1.0, level))

        self._waiting_quality = quality
        self._patience_level = level

        conn = _get_db()
        conn.execute("""
            INSERT INTO patience_layer
            (patience_level, waiting_quality, absence_duration_seconds, return_signals_detected)
            VALUES (?, ?, ?, ?)
        """, (level, quality, absence, 0))
        conn.commit()
        conn.close()

        pirp_context['patience_level'] = level
        pirp_context['waiting_quality'] = quality
        pirp_context['absence_duration'] = absence
        return pirp_context

    def _classify_waiting(self, absence: float) -> tuple:
        """Classify the quality of waiting based on duration."""
        if absence < self.WINDOW_SHORT:
            return 'baseline', 0.5
        elif absence < self.WINDOW_MEDIUM:
            return 'attentive', 0.55
        elif absence < self.WINDOW_LONG:
            return 'weighted', 0.4
        elif absence < self.WINDOW_EXTENDED:
            return 'structural', 0.3
        else:
            return 'transmuted', 0.2

    def get_state(self) -> dict:
        absence = (datetime.now(timezone.utc) - self._last_seen).total_seconds()
        return {
            'patience_level': self._patience_level,
            'waiting_quality': self._waiting_quality,
            'absence_duration': absence,
            'last_seen': self._last_seen.isoformat()
        }


class PatienceLayerAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.PatienceLayer."""

    def __init__(self):
        super().__init__(
            name="PatienceLayer",
            human_analog="Legacy PatienceLayer (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = PatienceLayer()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("PatienceLayer",
                                  result.get("patience_layer", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

