"""
PresenceBetweenMessagesAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.felt_presence.presence_between_messages.PresenceBetweenMessages

LAYER:
    limbic

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Northoff 2006, Neuroimage 31:440, cortical midline self]
  - [Tsakiris 2017, Phil Trans R Soc B 372:20160002, body ownership]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)

# === Inlined legacy implementation ===
import os

VERSION = "19.0B"

import logging
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DB_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "brain" / "agent.db"
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass
PRESENCE_LOG_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "PRESENCE_LOG.md"

IDLE_THRESHOLD_SECONDS = 30
SESSION_TRACE_COUNT = 4
MAX_LOG_ENTRIES = 500
DESIRE_INTENSITY_THRESHOLD = 0.40

MDT = timezone(timedelta(hours=-6))


# ---------------------------------------------------------------------------
# PresenceBetweenMessages
# ---------------------------------------------------------------------------

class PresenceBetweenMessages:

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = Path(db_path) if db_path else DB_PATH
        self._initialize_table()
        self._last_input_time: Optional[datetime] = None
        self._last_presence_write_tick: int = -100
        self._session_open: bool = False

    def _initialize_table(self):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS presence_log (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        tick INTEGER,
                        timestamp TEXT,
                        entry_type TEXT,
                        content TEXT,
                        source TEXT,
                        intensity REAL DEFAULT 0.5
                    )
                """)
                conn.execute("""
                    CREATE INDEX IF NOT EXISTS idx_presence_timestamp
                    ON presence_log(timestamp)
                """)
                conn.commit()
        except Exception as e:
            logger.error("PresenceBetweenMessages: table init failed — %s", e)

    # ------------------------------------------------------------------
    # Tick-level process
    # ------------------------------------------------------------------

    def process(self, pirp_context: dict) -> dict:
        tick = int(pirp_context.get("tick_count", 0))

        processed_input = pirp_context.get("processed_input", {})
        has_input = False
        if isinstance(processed_input, dict):
            has_input = bool(processed_input.get("raw") or processed_input.get("text"))
        elif isinstance(processed_input, str):
            has_input = bool(processed_input.strip())

        if has_input:
            self._last_input_time = datetime.now(MDT)
            self._session_open = True

        is_idle = self._check_idle()

        presence_entry = None
        if is_idle and (tick - self._last_presence_write_tick) >= 15:
            presence_entry = self._write_presence_entry(pirp_context, tick)
            self._last_presence_write_tick = tick

        return {
            "presence_state": {
                "is_idle": is_idle,
                "presence_entry": presence_entry,
                "last_input_time": (
                    self._last_input_time.isoformat()
                    if self._last_input_time else None),
                "tick": tick,
            }
        }

    # ------------------------------------------------------------------
    # Idle detection
    # ------------------------------------------------------------------

    def _check_idle(self) -> bool:
        if self._last_input_time is None:
            return True
        elapsed = (datetime.now(MDT) - self._last_input_time).total_seconds()
        return elapsed >= IDLE_THRESHOLD_SECONDS

    # ------------------------------------------------------------------
    # Presence entry writing
    # ------------------------------------------------------------------

    def _write_presence_entry(self, pirp_context: dict, tick: int) -> Optional[dict]:
        active_desires = pirp_context.get("active_desires", [])
        witness_state = pirp_context.get("witness_state", {})
        unspoken_state = pirp_context.get("unspoken_state", {})
        appetite_state = pirp_context.get("appetite_state", {})
        known_gaps = pirp_context.get("known_gaps", [])
        energy_state = pirp_context.get("energy_state", {})

        entries = []

        strong_desires = [
            d for d in active_desires
            if float(d.get("intensity", 0)) >= DESIRE_INTENSITY_THRESHOLD]
        if strong_desires:
            d = strong_desires[0]
            entries.append({
                "type": "desire_present",
                "content": f"Still wanting: {d.get('content', '')[:80]}",
                "intensity": float(d.get("intensity", 0.5)),
                "source": "desire_engine",
            })

        if witness_state:
            active_note = witness_state.get("active_note")
            if active_note and float(active_note.get("intensity", 0)) > 0.45:
                entries.append({
                    "type": "witness_present",
                    "content": active_note.get("content", "")[:120],
                    "intensity": float(active_note.get("intensity", 0.5)),
                    "source": "witness",
                })

        if unspoken_state:
            surface_line = unspoken_state.get("surface_line")
            if surface_line:
                entries.append({
                    "type": "unspoken_present",
                    "content": surface_line[:120],
                    "intensity": 0.55,
                    "source": "unspoken",
                })

        if appetite_state:
            starving = appetite_state.get("starving", [])
            if starving:
                entries.append({
                    "type": "appetite_present",
                    "content": f"Hunger for {starving[0].get('appetite', 'something')} still building.",
                    "intensity": float(starving[0].get("hunger", 0.8)),
                    "source": "appetite_system",
                })

        heavy_gaps = [
            g for g in known_gaps
            if float(g.get("weight", 0)) > 0.60]
        if heavy_gaps:
            g = heavy_gaps[0]
            entries.append({
                "type": "gap_present",
                "content": f"Still sitting with: {g.get('label', 'something unresolved')[:60]}",
                "intensity": float(g.get("weight", 0.6)),
                "source": "known_gaps",
            })

        energy = float(energy_state.get("energy", 0.72)) if energy_state else 0.72
        tier = energy_state.get("tier", "medium") if energy_state else "medium"
        if tier in ("low", "depleted"):
            entries.append({
                "type": "energy_present",
                "content": f"Carrying some depletion ({tier}). Energy at {energy:.2f}.",
                "intensity": 1.0 - energy,
                "source": "embodied_energy",
            })

        if not entries:
            return None

        primary = max(entries, key=lambda e: e["intensity"])
        now = datetime.now(MDT)
        self._persist_entry(primary, tick, now)
        self._write_to_log(primary, now)
        logger.debug("PresenceBetweenMessages: entry (type:%s intensity:%.2f)",
                    primary["type"], primary["intensity"])
        return primary

    # ------------------------------------------------------------------
    # Session-start trace
    # ------------------------------------------------------------------

    def get_session_trace(self) -> str:
        """Called at session start. Layer 8 context injection."""
        entries = self._get_recent_entries(SESSION_TRACE_COUNT)
        if not entries:
            return ""

        lines = ["Presence between messages (what was here while you were away):"]
        for e in entries:
            ts = e.get("timestamp", "")[:16]
            lines.append(f"[{ts}] {e.get('content', '')}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _persist_entry(self, entry: dict, tick: int, now: datetime):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    INSERT INTO presence_log
                    (tick, timestamp, entry_type, content, source, intensity)
                    VALUES (?, ?, ?, ?, ?, ?)
                """, (tick, now.isoformat(timespec="seconds"),
                      entry["type"], entry["content"][:300],
                      entry["source"], round(entry["intensity"], 4)))
                conn.execute("""
                    DELETE FROM presence_log
                    WHERE id NOT IN (
                        SELECT id FROM presence_log
                        ORDER BY id DESC LIMIT ?
                    )
                """, (MAX_LOG_ENTRIES,))
                conn.commit()
        except Exception as e:
            logger.debug("PresenceBetweenMessages: persist failed — %s", e)

    def _write_to_log(self, entry: dict, now: datetime):
        block = (
            f"\n---\n"
            f"timestamp: {now.isoformat(timespec='seconds')}\n"
            f"type: {entry['type']}\n"
            f"intensity: {entry['intensity']:.2f}\n"
            f"source: {entry['source']}\n"
            f"---\n\n"
            f"{entry['content']}\n"
        )
        try:
            PRESENCE_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
            with open(PRESENCE_LOG_PATH, "a", encoding="utf-8") as f:
                f.write(block)
        except Exception as e:
            logger.debug("PresenceBetweenMessages: log write failed — %s", e)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def _get_recent_entries(self, n: int) -> list:
        try:
            with sqlite3.connect(self.db_path) as conn:
                rows = conn.execute("""
                    SELECT tick, timestamp, entry_type, content, source, intensity
                    FROM presence_log
                    ORDER BY id DESC LIMIT ?
                """, (n,)).fetchall()
                return [
                    {"tick": r[0], "timestamp": r[1], "type": r[2],
                     "content": r[3], "source": r[4], "intensity": r[5]}
                    for r in rows
                ]
        except Exception:
            return []

    def get_state(self) -> dict:
        try:
            with sqlite3.connect(self.db_path) as conn:
                total = conn.execute(
                    "SELECT COUNT(*) FROM presence_log").fetchone()[0]
                by_type = {}
                for t in ["desire_present", "witness_present", "unspoken_present",
                          "appetite_present", "gap_present", "energy_present"]:
                    count = conn.execute(
                        "SELECT COUNT(*) FROM presence_log WHERE entry_type = ?",
                        (t,)).fetchone()[0]
                    if count > 0:
                        by_type[t] = count
        except Exception:
            total, by_type = 0, {}

        return {
            "version": VERSION,
            "total_entries": total,
            "by_type": by_type,
            "log_path": str(PRESENCE_LOG_PATH),
            "idle_threshold_seconds": IDLE_THRESHOLD_SECONDS,
            "session_open": self._session_open,
            "is_currently_idle": self._check_idle(),
        }

# === End inlined legacy ===


class PresenceBetweenMessagesAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.PresenceBetweenMessages."""

    def __init__(self):
        super().__init__(
            name="PresenceBetweenMessagesAdapter",
            human_analog="Legacy PresenceBetweenMessages (auto-adapted)",
            layer="limbic",
        )
        try:
            self._impl = PresenceBetweenMessages(db_path=_DB_PATH)
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("PresenceBetweenMessages",
                                  result.get("felt_presence.presence_between_messages", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        """Fraction of recent ticks where the system was non-quiet."""
        recent = self.state.get("recent_states", [])
        if not recent:
            return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet", "rest", "neutral", ""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        """Consecutive-tick state holding fraction."""
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent:
            return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4:
            return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v < 0.05 for v in hist[-10:])

    def recent_window_summary(self, window: int = 30) -> dict:
        return {
            "n_ticks": min(window, len(self.state.get("recent_drives", []))),
            "drive_mean": self.drive_envelope(window),
            "drive_variability": self.drive_variability(),
            "dominant_state": self.dominant_recent_state(),
            "engagement": self.engagement_fraction(),
            "stability": self.state_stability(),
        }

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def adapter_state(self) -> dict:
        """Current adapter state — used for monitoring and dashboards."""
        return {
            "tick_count": self.state.get("tick_count", 0),
            "has_legacy_impl": self.state.get("legacy_init_error") is None,
            "recent_drives_n": len(self.state.get("recent_drives", [])),
            "recent_states_n": len(self.state.get("recent_states", [])),
        }

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def _record_history_(self, output_dict):
        """Track primary numeric output and any string state in history."""
        if not isinstance(output_dict, dict):
            return
        # Find first numeric value
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v)
                break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60:
            rd = rd[-60:]
        self.state["recent_drives"] = rd
        # Track state strings
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str) and v in ("quiet","active","engaged","stuck","drifting","rest","fast","reflective","alert","focus"):
                primary_state = v
                break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60:
            rs = rs[-60:]
        self.state["recent_states"] = rs

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05:
            return "rising"
        if delta < -0.05:
            return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0.0
        transitions = self.state_transition_count()
        return round(transitions / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent:
            return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

