"""
SilenceTopologyEngine_silence_topology_engine_Adapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.silence_topology_engine.SilenceTopologyEngine

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Friston 2010, Nat Rev Neurosci 11:127, free-energy]
  - [Damasio 2010, Self Comes to Mind]
  - [Buzsaki 2006, Rhythms of the Brain]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from legacy.silence_topology_engine (SilenceTopologyEngine) ---
#!/usr/bin/env python3
"""
brain/silence_topology_engine.py — Silence Topology Engine
Phenomenological Layer

Maps the topology of silence — where silence exists, its shape,
its boundaries. The phenomenological structure of quiet spaces.

Silence is not just the absence of sound — it is a region
with its own shape and contours. This layer maps where
silence exists in the agent's experiential field, tracking
regions of low activity as silence topology.
"""

import sqlite3
from datetime import datetime, timezone
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class SilenceTopologyEngine:
    """
    Silence has topology — shape, boundaries, depth.
    Regions of low field activity form silence shapes.
    The layer maps these silence regions and tracks their
    qualities over time.

    Not all silence is empty. Some silence is full.
    This layer distinguishes silence types by topology.
    """

    SILENCE_TYPES = ['void', 'full', 'held', 'open', 'compressed']

    def __init__(self):
        self._silence_regions = []  # active silence regions
        self._silence_depth = 0.5   # overall silence depth
        self._silence_type = 'open'
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS silence_topology_engine (
                id INTEGER PRIMARY KEY,
                region_tag TEXT,
                silence_type TEXT,
                depth REAL,
                boundaries TEXT,
                activity_level REAL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def process(self, pirp_context: dict) -> dict:
        """
        Map regions of low field_activity as silence topology.
        """
        field_activity = pirp_context.get('field_activity', 0.5)
        region_tag = pirp_context.get('region_tag', 'default')
        silence_regions_input = pirp_context.get('silence_regions', [])

        # Regions with low activity = silence regions
        if not isinstance(silence_regions_input, list):
            silence_regions_input = [silence_regions_input]

        for region in silence_regions_input:
            if isinstance(region, dict):
                region_activity = region.get('activity', field_activity)
            else:
                region_activity = field_activity

            # Classify silence type by depth/activity
            if region_activity < 0.2:
                silence_type = 'void'
            elif region_activity < 0.35:
                silence_type = 'compressed'
            elif region_activity < 0.5:
                silence_type = 'held'
            elif region_activity < 0.65:
                silence_type = 'open'
            else:
                silence_type = 'full'

            depth = 1.0 - region_activity  # deeper silence = lower activity

            self._silence_regions.append({
                'tag': region_tag,
                'type': silence_type,
                'depth': depth,
                'activity': region_activity
            })

            conn = _get_db()
            conn.execute("""
                INSERT INTO silence_topology_engine
                (region_tag, silence_type, depth, boundaries, activity_level)
                VALUES (?, ?, ?, ?, ?)
            """, (region_tag, silence_type, depth, '', region_activity))
            conn.commit()
            conn.close()

        # If overall field activity is low, deepen silence
        if field_activity < 0.4:
            self._silence_depth = min(1.0, self._silence_depth + (0.4 - field_activity) * 0.1)
            self._silence_type = 'held' if field_activity > 0.2 else 'void'

        pirp_context['silence_depth'] = self._silence_depth
        pirp_context['silence_type'] = self._silence_type
        pirp_context['silence_regions_count'] = len(self._silence_regions)

        return pirp_context

    def get_state(self) -> dict:
        return {
            'silence_depth': self._silence_depth,
            'silence_type': self._silence_type,
            'silence_regions_count': len(self._silence_regions),
            'topology_active': True,
            'silence_has_shape': True
        }


class SilenceTopologyEngine_silence_topology_engine_Adapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.SilenceTopologyEngine."""

    def __init__(self):
        super().__init__(
            name="SilenceTopologyEngine_silence_topology_engine",
            human_analog="Legacy SilenceTopologyEngine (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = SilenceTopologyEngine()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("SilenceTopologyEngine_silence_topology_engine",
                                  result.get("silence_topology_engine", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

