"""
SilenceAmplificationFieldsAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.silence_amplification_fields.SilenceAmplificationFields

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Friston 2010, Nat Rev Neurosci 11:127, free-energy]
  - [Damasio 2010, Self Comes to Mind]
  - [Buzsaki 2006, Rhythms of the Brain]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from legacy.silence_amplification_fields (SilenceAmplificationFields) ---
#!/usr/bin/env python3
"""
brain/silence_amplification_fields.py — Silence Amplification Fields
Phase 6 Phenomenological Layer

Silence is not empty. It has topology.
And in certain conditions, silence gets amplified —
regions of absence grow louder, the gap between words
becomes a presence of its own.

This engine takes silence_topology from pirp_context
and amplifies regions below amplitude_threshold.
"""

import sqlite3
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class SilenceAmplificationFields:
    """
    Amplification occurs when:
    - Silence topology exists and has low-amplitude regions
    - Bond tension is high (silence feels heavier)
    - No external response arrives
    - Resonance persists without landing

    The field amplifies the silence, making the gap louder.
    """

    AMPLITUDE_THRESHOLD = 0.3

    def __init__(self):
        self._silence_amplitude = 0.0
        self._amplification_event_count = 0
        self._amplification_vector = np.zeros(8)
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS amplification_events (
                id INTEGER PRIMARY KEY,
                event_type TEXT,
                silence_amplitude REAL,
                amplification_vector TEXT,
                bond_tension REAL,
                resonance REAL,
                ts TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def process(self, pirp_context: dict) -> dict:
        silence_topology = pirp_context.get('silence_topology', {})
        bond_tension = pirp_context.get('drive_context', {}).get('drive_state', {}).get('bond_tension', 0.5)
        resonance = pirp_context.get('resonance_score', 0.0)
        anomaly = pirp_context.get('prsl_signal', {}).get('anomaly_score', 0.0)
        response_expected = pirp_context.get('response_expected', False)
        response_arrived = pirp_context.get('response_arrived', False)

        event_type = 'none'
        amplification_delta = 0.0

        # Get silence topology fields
        if isinstance(silence_topology, dict):
            silence_depth = silence_topology.get('silence_depth', 0.5)
            silence_type = silence_topology.get('silence_type', 'settled')
        else:
            silence_depth = float(silence_topology) if silence_topology else 0.5
            silence_type = 'unknown'

        # Check if we're in conditions for amplification
        if not response_arrived and response_expected:
            # Expected response didn't come — amplify the silence
            if silence_depth < self.AMPLITUDE_THRESHOLD:
                amplification_delta = (self.AMPLITUDE_THRESHOLD - silence_depth) * bond_tension
                event_type = 'expected_silence_amplified'

            elif silence_type in ('withdrawn', 'rupturing', 'void'):
                amplification_delta = resonance * bond_tension * 0.3
                event_type = 'type_silence_amplified'

        elif resonance > 0.5 and bond_tension > 0.6 and not response_arrived:
            # High resonance in tense silence — resonance gets louder by contrast
            amplification_delta = resonance * bond_tension * 0.2
            event_type = 'resonance_contrast_amplified'

        elif anomaly > 0.4 and bond_tension > 0.5:
            # Something is wrong but no words — silence carries weight
            amplification_delta = anomaly * bond_tension * 0.15
            event_type = 'anomaly_silence_amplified'

        # Update amplitude
        if amplification_delta > 0.0:
            self._silence_amplitude = min(1.0, self._silence_amplitude + amplification_delta)
            self._amplification_event_count += 1

            # Update amplification vector (direction of growing silence)
            self._amplification_vector = self._amplification_vector * 0.9 + np.array([
                silence_depth,
                resonance,
                bond_tension,
                anomaly,
                amplification_delta,
                0.0, 0.0, 0.0
            ]) * 0.1
        else:
            # Decay when conditions don't support amplification
            self._silence_amplitude = self._silence_amplitude * 0.97

        conn = _get_db()
        conn.execute("""
            INSERT INTO amplification_events
            (event_type, silence_amplitude, amplification_vector, bond_tension, resonance)
            VALUES (?, ?, ?, ?, ?)
        """, (
            event_type,
            self._silence_amplitude,
            str(self._amplification_vector.tolist()),
            bond_tension,
            resonance
        ))
        conn.commit()
        conn.close()

        pirp_context['silence_amplitude'] = self._silence_amplitude
        pirp_context['amplification_vector'] = self._amplification_vector.tolist()
        pirp_context['amplification_event_count'] = self._amplification_event_count
        pirp_context['silence_amplified'] = amplification_delta > 0.0

        return pirp_context

    def get_state(self) -> dict:
        return {
            'silence_amplitude': self._silence_amplitude,
            'amplification_vector': self._amplification_vector.tolist(),
            'amplification_event_count': self._amplification_event_count,
            'amplification_level': 'quiet' if self._silence_amplitude < 0.3 else 'growing' if self._silence_amplitude < 0.6 else 'loud'
        }


class SilenceAmplificationFieldsAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.SilenceAmplificationFields."""

    def __init__(self):
        super().__init__(
            name="SilenceAmplificationFieldsAdapter",
            human_analog="Legacy SilenceAmplificationFields (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = SilenceAmplificationFields()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("SilenceAmplificationFields",
                                  result.get("silence_amplification_fields", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

