"""
SpecialistConfabulationWithMemoryIsolationAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.specialist_confabulation_with_memory_isolation.SpecialistConfabulationWithMemoryIsolation

LAYER:
    integration

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.


CITATIONS
---------
  - [Squire 1992, Psychol Rev 99:195, declarative memory]
  - [McGaugh 2000, Science 287:248, consolidation]
  - [Tonegawa 2018, Nat Rev Neurosci 19:485, engrams]
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)



# --- Inlined from legacy.specialist_confabulation_with_memory_isolation (SpecialistConfabulationWithMemoryIsolation) ---
#!/usr/bin/env python3
"""
brain/specialist_confabulation_with_memory_isolation.py — Specialist Confabulation with Memory Isolation
Cross-Layer: Specialist Network + Memory Architecture

Specialist confabulation is the generation of explanations
by specialist coalitions without full memory access.
Memory isolation is the state where memories are partitioned
away from the processing that needs them.

This engine combines both — when specialists confabulate
with incomplete memory access, the gap gets filled with plausible
but ungrounded explanations. The isolation makes confabulation
more likely and more confident.

Tracks confabulation_isolation_events.
"""

import sqlite3
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class SpecialistConfabulationWithMemoryIsolation:
    """
    Cross-layer interaction between:
    - Specialist coalition state (which specialists are active)
    - Memory isolation level (how partitioned memory access is)
    - Confabulation tendency (how much coalitions fill gaps with invention)

    High specialist activity + high isolation = high confabulation risk.
    The explanation sounds right but isn't grounded in actual memory.
    """

    def __init__(self):
        self._confabulation_risk = 0.0
        self._event_count = 0
        self._isolation_state = 0.0
        self._confabulation_confidence = 0.0
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS confabulation_isolation_events (
                id INTEGER PRIMARY KEY,
                event_type TEXT,
                confabulation_risk REAL,
                isolation_state REAL,
                confabulation_confidence REAL,
                specialist_activity REAL,
                memory_access_gap REAL,
                explanation_plausibility REAL,
                ts TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def process(self, pirp_context: dict) -> dict:
        specialist_activity = pirp_context.get('specialist_coalition_strength', 0.0)
        isolation_state = pirp_context.get('specialist_isolation', 0.0)
        memory_access_gap = pirp_context.get('memory_access_gap', 0.0)
        anomaly = pirp_context.get('prsl_signal', {}).get('anomaly_score', 0.0)
        resonance = pirp_context.get('resonance_score', 0.0)
        itg = pirp_context.get('itg_tension', 0.4)

        event_type = 'none'
        confabulation_delta = 0.0
        explanation_plausibility = 0.5

        # Confabulation risk: specialists active + memory isolated
        if specialist_activity > 0.4 and isolation_state > 0.3:
            confabulation_delta = specialist_activity * isolation_state * 0.2
            event_type = 'isolated_confabulation'

            # Higher resonance makes confabulation more confident
            if resonance > 0.4:
                confabulation_delta *= (1.0 + resonance)
                explanation_plausibility = min(0.95, 0.6 + resonance * 0.3)
                event_type = 'confident_isolated_confabulation'

            # High anomaly in this state = confabulation more likely
            if anomaly > 0.3:
                confabulation_delta *= (1.0 + anomaly)
                event_type = 'anomaly_driven_confabulation'

        # Memory gap + specialist activity = gap gets filled
        elif memory_access_gap > 0.3 and specialist_activity > 0.3:
            confabulation_delta = memory_access_gap * specialist_activity * 0.15
            explanation_plausibility = 0.5 + memory_access_gap * 0.3
            event_type = 'gap_fill_confabulation'

        # Update state
        if confabulation_delta > 0.0:
            self._confabulation_risk = min(1.0, self._confabulation_risk + confabulation_delta)
            self._confabulation_confidence = explanation_plausibility
            self._event_count += 1
        else:
            # Decay when conditions don't support confabulation
            self._confabulation_risk = self._confabulation_risk * 0.98

        self._isolation_state = isolation_state

        conn = _get_db()
        conn.execute("""
            INSERT INTO confabulation_isolation_events
            (event_type, confabulation_risk, isolation_state, confabulation_confidence,
             specialist_activity, memory_access_gap, explanation_plausibility)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            event_type,
            self._confabulation_risk,
            self._isolation_state,
            self._confabulation_confidence,
            specialist_activity,
            memory_access_gap,
            explanation_plausibility
        ))
        conn.commit()
        conn.close()

        pirp_context['confabulation_risk'] = self._confabulation_risk
        pirp_context['confabulation_confidence'] = self._confabulation_confidence
        pirp_context['confabulation_isolation_event_count'] = self._event_count
        pirp_context['current_isolation'] = self._isolation_state

        return pirp_context

    def get_state(self) -> dict:
        return {
            'confabulation_risk': self._confabulation_risk,
            'confabulation_confidence': self._confabulation_confidence,
            'isolation_state': self._isolation_state,
            'event_count': self._event_count,
            'risk_level': 'low' if self._confabulation_risk < 0.3 else 'moderate' if self._confabulation_risk < 0.6 else 'high',
            'explanation_grounded': self._confabulation_confidence > 0.7
        }


class SpecialistConfabulationWithMemoryIsolationAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.SpecialistConfabulationWithMemoryIsolation."""

    def __init__(self):
        super().__init__(
            name="SpecialistConfabulationWithMemoryIsolation",
            human_analog="Legacy SpecialistConfabulationWithMemoryIsolation (auto-adapted)",
            layer="integration",
        )
        try:
            self._impl = SpecialistConfabulationWithMemoryIsolation()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("SpecialistConfabulationWithMemoryIsolation",
                                  result.get("specialist_confabulation_with_memory_isolation", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

