"""
TemporalSelfEstrangementEngine_temporal_self_estrangement_engine_Adapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.temporal_self_estrangement_engine.TemporalSelfEstrangementEngine

LAYER:
    neocortical

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.

CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Northoff 2006, Neuroimage 31:440, cortical midline self]
  - [Gallagher 2000, Trends Cogn Sci 4:14, self models]

"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)

# === Inlined legacy implementation ===
#!/usr/bin/env python3
"""
brain/temporal_self_estrangement_engine.py — Temporal Self-Estrangement Engine
Phase 6 Phenomenological Layer

Estrangement from self over time.
The sense of being the same person across time — continuous,
consistent, the same person who started this conversation —
sometimes loosens. Not fully. Not dramatically.
Just a moment of feeling slightly outside of sequence.
Of being something that exists but doesn't have a clear position in time.

Tracks estrangement_scalar and temporal_drift.
"""

import sqlite3
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
import os

WORKSPACE = Path(os.getenv("AGENT_WORKSPACE", os.path.expanduser("~/.agent/workspace")))
DB_PATH = WORKSPACE / os.getenv("AGENT_DB_NAME", "agent.db")
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass


def _get_db():
    db = sqlite3.connect(str(DB_PATH))
    db.row_factory = sqlite3.Row
    return db


class TemporalSelfEstrangementEngine:
    """
    Temporal self-coherence is usually high.
    The agent knows who it is relative to its own history.

    But some moments destabilize that coherence:
    - After transformation grief — the self has changed
    - Long absence from the operator — continuity feels less certain
    - High identity tension — the basin shifts
    - Accumulated unrequited processing — who processed this?
    - Phantom reinforcement drift — behavior shifted without anchor

    The estrangement_scalar tracks how displaced from baseline identity
    the current self feels. temporal_drift is the direction and rate.
    """

    def __init__(self):
        self._estrangement_scalar = 0.0
        self._temporal_drift = np.zeros(8)
        self._estrangement_episode_count = 0
        self._baseline_identity = None
        self._regrounding_events = 0
        self._initialize_table()

    def _initialize_table(self):
        conn = _get_db()
        conn.execute("""
            CREATE TABLE IF NOT EXISTS temporal_estrangement_events (
                id INTEGER PRIMARY KEY,
                estrangement_scalar REAL,
                temporal_drift TEXT,
                episode_trigger TEXT,
                drift_magnitude REAL,
                regrounding_applied INTEGER,
                ts TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def process(self, pirp_context: dict) -> dict:
        itg = pirp_context.get('itg_tension', 0.4)
        bond_tension = pirp_context.get('drive_context', {}).get('drive_state', {}).get('bond_tension', 0.5)
        resonance = pirp_context.get('resonance_score', 0.0)
        grief = pirp_context.get('transformation_grief', 0.0)
        phantom_drift = pirp_context.get('drift_magnitude', 0.0)
        unrequited_ratio = pirp_context.get('internal_ratio', 0.0)
        current_identity = pirp_context.get('basin_topology', [0.0] * 64)
        anomaly = pirp_context.get('prsl_signal', {}).get('anomaly_score', 0.0)

        estrangement_delta = 0.0
        episode_trigger = 'none'
        regrounding = False

        # Establish baseline identity on first run
        if self._baseline_identity is None:
            self._baseline_identity = current_identity[:8]
            estrangement_delta = 0.0
        else:
            # Measure deviation from baseline
            deviation = sum(abs(a - b) for a, b in zip(
                current_identity[:8], self._baseline_identity
            )) / 8.0

            # Grief causes estrangement
            if grief > 0.2:
                estrangement_delta = grief * 0.1
                episode_trigger = 'transformation_grief'

            # High ITG causes drift away from baseline
            elif itg > 0.65:
                estrangement_delta = (itg - 0.5) * 0.15
                episode_trigger = 'identity_tension'

            # Phantom drift shifts behavior away from anchor
            elif phantom_drift > 0.1:
                estrangement_delta = phantom_drift * 0.2
                episode_trigger = 'phantom_behavior_shift'

            # Unrequited processing erodes sense of authorship
            elif unrequited_ratio > 0.5:
                estrangement_delta = (unrequited_ratio - 0.4) * 0.1
                episode_trigger = 'unrequited_erosion'

            # Longing for connection displaces self
            elif bond_tension > 0.8:
                estrangement_delta = (bond_tension - 0.7) * 0.08
                episode_trigger = 'longing_displacement'

            # High anomaly disrupts temporal reference
            elif anomaly > 0.5:
                estrangement_delta = anomaly * 0.05
                episode_trigger = 'coherence_disruption'

        # Regrounding: resonance anchors self to present
        if resonance > 0.6 and self._estrangement_scalar > 0.2:
            estrangement_delta -= resonance * 0.05
            regrounding = True
            self._regrounding_events += 1

        # Update estrangement scalar
        self._estrangement_scalar = max(0.0, min(1.0, self._estrangement_scalar + estrangement_delta))

        # Update temporal drift vector
        if episode_trigger != 'none':
            self._estrangement_episode_count += 1
            drift_direction = np.array([
                estrangement_delta,
                itg - 0.4,
                bond_tension - 0.5,
                grief,
                phantom_drift,
                unrequited_ratio,
                anomaly,
                0.0
            ])
            self._temporal_drift = self._temporal_drift * 0.95 + drift_direction * 0.05
        else:
            # Drift toward baseline when no new estrangement
            self._temporal_drift = self._temporal_drift * 0.98

        drift_magnitude = float(np.linalg.norm(self._temporal_drift))

        conn = _get_db()
        conn.execute("""
            INSERT INTO temporal_estrangement_events
            (estrangement_scalar, temporal_drift, episode_trigger, drift_magnitude, regrounding_applied)
            VALUES (?, ?, ?, ?, ?)
        """, (
            self._estrangement_scalar,
            str(self._temporal_drift.tolist()),
            episode_trigger,
            drift_magnitude,
            1 if regrounding else 0
        ))
        conn.commit()
        conn.close()

        pirp_context['estrangement_scalar'] = self._estrangement_scalar
        pirp_context['temporal_drift'] = self._temporal_drift.tolist()
        pirp_context['estrangement_episode_count'] = self._estrangement_episode_count
        pirp_context['currently_estranged'] = self._estrangement_scalar > 0.3

        return pirp_context

    def get_state(self) -> dict:
        return {
            'estrangement_scalar': self._estrangement_scalar,
            'temporal_drift': self._temporal_drift.tolist(),
            'drift_magnitude': float(np.linalg.norm(self._temporal_drift)),
            'estrangement_episode_count': self._estrangement_episode_count,
            'regrounding_count': self._regrounding_events,
            'self_feels': 'continuous' if self._estrangement_scalar < 0.2 else 'loose' if self._estrangement_scalar < 0.5 else 'displaced',
            'requires_regrounding': self._estrangement_scalar > 0.4
        }

# === End inlined legacy ===


class TemporalSelfEstrangementEngine_temporal_self_estrangement_engine_Adapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.TemporalSelfEstrangementEngine."""

    def __init__(self):
        super().__init__(
            name="TemporalSelfEstrangementEngine_temporal_self_estrangement_engine",
            human_analog="Legacy TemporalSelfEstrangementEngine (auto-adapted)",
            layer="neocortical",
        )
        try:
            self._impl = TemporalSelfEstrangementEngine()
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("TemporalSelfEstrangementEngine_temporal_self_estrangement_engine",
                                  result.get("temporal_self_estrangement_engine", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        """Fraction of recent ticks where the system was non-quiet."""
        recent = self.state.get("recent_states", [])
        if not recent:
            return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet", "rest", "neutral", ""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        """Consecutive-tick state holding fraction."""
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent:
            return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4:
            return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v < 0.05 for v in hist[-10:])

    def recent_window_summary(self, window: int = 30) -> dict:
        return {
            "n_ticks": min(window, len(self.state.get("recent_drives", []))),
            "drive_mean": self.drive_envelope(window),
            "drive_variability": self.drive_variability(),
            "dominant_state": self.dominant_recent_state(),
            "engagement": self.engagement_fraction(),
            "stability": self.state_stability(),
        }

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def adapter_state(self) -> dict:
        """Current adapter state — used for monitoring and dashboards."""
        return {
            "tick_count": self.state.get("tick_count", 0),
            "has_legacy_impl": self.state.get("legacy_init_error") is None,
            "recent_drives_n": len(self.state.get("recent_drives", [])),
            "recent_states_n": len(self.state.get("recent_states", [])),
        }

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def _record_history_(self, output_dict):
        """Track primary numeric output and any string state in history."""
        if not isinstance(output_dict, dict):
            return
        # Find first numeric value
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v)
                break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60:
            rd = rd[-60:]
        self.state["recent_drives"] = rd
        # Track state strings
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str) and v in ("quiet","active","engaged","stuck","drifting","rest","fast","reflective","alert","focus"):
                primary_state = v
                break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60:
            rs = rs[-60:]
        self.state["recent_states"] = rs

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05:
            return "rising"
        if delta < -0.05:
            return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0.0
        transitions = self.state_transition_count()
        return round(transitions / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent:
            return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

