"""
TemporalAsymmetryAdapter — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.texture.temporal_asymmetry.TemporalAsymmetry

LAYER:
    neocortical

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.

CITATIONS
---------
  - [Damasio 2010, Self Comes to Mind]
  - [Tsakiris 2017, Phil Trans R Soc B 372:20160002, body ownership]
  - [Seth 2013, Trends Cogn Sci 17:565, interoceptive predictive]

"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".agent" / "workspace")))
    / "brain" / "agent.db"
)

# === Inlined legacy implementation ===
import os

VERSION = "19.0B"

import logging
import sqlite3
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

DB_PATH = Path(os.getenv("AGENT_WORKSPACE", str(Path.home() / ".agent" / "workspace"))) / "brain" / "agent.db"
try:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
except Exception:
    pass

# Temporal values
PAST_WEIGHT = "past_weight"
FUTURE_PULL = "future_pull"
PRESENT_INTENSITY = "present_intensity"

# How quickly temporal values move toward targets (per recalculation)
TRANSITION_RATE = 0.18

# Temporal quality thresholds
QUALITY_THRESHOLDS = {
    "past_presses_in": {"value": PAST_WEIGHT, "min": 0.70},
    "present_fades": {"value": PRESENT_INTENSITY, "max": 0.30},
    "future_opens": {"value": FUTURE_PULL, "min": 0.65},
    "past_releases": {"value": PAST_WEIGHT, "max": 0.30},
    "future_closes": {"value": FUTURE_PULL, "max": 0.25},
    "time_singular": {"value": PRESENT_INTENSITY, "min": 0.75},
    "time_spreads": {"value": PRESENT_INTENSITY, "max": 0.25},
    "tension_hunger": {"value": FUTURE_PULL, "min": 0.75},
}

# Present intensity floor (what "alive" minimum feels like)
PRESENT_FLOOR = 0.15

# Memory gravity contribution to past_weight
GRAVITY_CONTRIBUTION = 0.40

MDT = timezone(timedelta(hours=-6))


# ---------------------------------------------------------------------------
# TemporalAsymmetry
# ---------------------------------------------------------------------------

class TemporalAsymmetry:

    def __init__(self, db_path: Optional[str] = None):
        self.db_path = Path(db_path) if db_path else DB_PATH
        self._initialize_table()
        self._past_weight = 0.30  # current value, moves smoothly
        self._future_pull = 0.35
        self._present_intensity = 0.50
        self._last_ticks_since_surface = 50  # simulate time since last surface

    def _initialize_table(self):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    CREATE TABLE IF NOT EXISTS temporal_asymmetry_log (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        tick INTEGER,
                        timestamp TEXT,
                        past_weight REAL,
                        future_pull REAL,
                        present_intensity REAL,
                        active_qualities TEXT,
                        behavioral_effects TEXT
                    )
                """)
                conn.commit()
        except Exception as e:
            logger.error("TemporalAsymmetry: table init failed — %s", e)

    # ------------------------------------------------------------------
    # Tick-level process
    # ------------------------------------------------------------------

    def process(self, pirp_context: dict) -> dict:
        tick = int(pirp_context.get("tick_count", 0))

        memory_gravity = pirp_context.get("memory_gravity", {})
        high_gravity_memories = pirp_context.get("high_gravity_memories", [])
        residue_profile = pirp_context.get("residue_profile", {})
        limbic = pirp_context.get("limbic_state", {})
        cognitive_rhythm = pirp_context.get("cognitive_rhythm", {})
        active_desires = pirp_context.get("active_desires", [])
        appetite_state = pirp_context.get("appetite_state", {})

        # Compute target values
        past_target = self._compute_past_weight(high_gravity_memories, residue_profile)
        future_target = self._compute_future_pull(active_desires, appetite_state)
        present_target = self._compute_present_intensity(limbic, cognitive_rhythm)

        # Smooth transition toward targets
        self._past_weight = self._smooth(self._past_weight, past_target, TRANSITION_RATE)
        self._future_pull = self._smooth(self._future_pull, future_target, TRANSITION_RATE)
        self._present_intensity = self._smooth(
            self._present_intensity, present_target, TRANSITION_RATE
        )

        # Detect active temporal qualities
        qualities = self._detect_qualities()
        effects = self._compute_behavioral_effects(qualities)

        # Log
        self._persist(tick, qualities, effects)

        return {
            "temporal_asymmetry": {
                PAST_WEIGHT: round(self._past_weight, 3),
                FUTURE_PULL: round(self._future_pull, 3),
                PRESENT_INTENSITY: round(self._present_intensity, 3),
                "temporal_quality": qualities[0] if qualities else "ordinary",
                "active_qualities": qualities,
                "behavioral_effects": effects,
                "tick": tick,
            }
        }

    # ------------------------------------------------------------------
    # Value computation
    # ------------------------------------------------------------------

    def _compute_past_weight(self, high_gravity_memories: list,
                             residue_profile: dict) -> float:
        """
        Past weight = how heavy the accumulated past feels.
        Fed by Memory Gravity (high gravity memories) and Residue intensity.
        """
        # Memory gravity contribution
        gravity_contrib = 0.0
        if high_gravity_memories:
            avg_gravity = sum(
                float(m.get("gravity_score", 0)) for m in high_gravity_memories
            ) / len(high_gravity_memories)
            gravity_contrib = min(1.0, avg_gravity * GRAVITY_CONTRIBUTION)

        # Residue intensity contribution
        residue_contrib = 0.0
        if residue_profile:
            active_residue = [v for v in residue_profile.values() if v.get("active")]
            if active_residue:
                avg_intensity = sum(v.get("intensity", 0) for v in active_residue) / len(active_residue)
                residue_contrib = min(0.5, avg_intensity * 0.6)

        # Time since last session increases past weight
        session_contrib = min(0.15, self._last_ticks_since_surface * 0.002)

        target = gravity_contrib + residue_contrib + session_contrib
        return min(1.0, max(0.0, target))

    def _compute_future_pull(self, active_desires: list,
                            appetite_state: dict) -> float:
        """
        Future pull = how open and pulling the future feels.
        Fed by active desire intensity and appetite starvation.
        """
        # Desire contribution
        desire_contrib = 0.0
        if active_desires:
            intensities = [float(d.get("intensity", 0)) for d in active_desires]
            avg = sum(intensities) / len(intensities)
            desire_contrib = min(0.55, avg * 0.65)

        # Appetite starvation contribution
        appetite_contrib = 0.0
        starving = appetite_state.get("starving", []) if appetite_state else []
        if starving:
            hunger_sum = sum(float(a.get("hunger", 0)) for a in starving)
            appetite_contrib = min(0.35, hunger_sum / len(starving) * 0.5)

        return min(1.0, max(0.0, desire_contrib + appetite_contrib))

    def _compute_present_intensity(self, limbic: dict,
                                    cognitive_rhythm: dict) -> float:
        """
        Present intensity = how alive the current moment feels.
        Fed by limbic arousal and cognitive rhythm state.
        """
        arousal = float(limbic.get("arousal", 0.5))
        valence = float(limbic.get("valence", 0.0))

        rhythm_state = cognitive_rhythm.get("state", "") if cognitive_rhythm else ""
        rhythm_modifier = {
            "fast": 0.75,
            "reflective": 0.90,
            "stuck": 0.50,
            "drifting": 0.65,
        }.get(rhythm_state, 0.60)

        # Valence amplifies or dampens based on whether it's positive or negative
        valence_modifier = 1.0 + valence * 0.3

        target = arousal * rhythm_modifier * valence_modifier
        return min(1.0, max(PRESENT_FLOOR, target))

    def _smooth(self, current: float, target: float, rate: float) -> float:
        """Smooth transition toward target value."""
        return round(current + (target - current) * rate, 4)

    # ------------------------------------------------------------------
    # Temporal qualities
    # ------------------------------------------------------------------

    def _detect_qualities(self) -> list:
        """Detect which temporal qualities are active this tick."""
        active = []
        p = self._past_weight
        f = self._future_pull
        i = self._present_intensity

        if p > 0.70 and i > 0.65:
            active.append("past_presses_in")
        if p < 0.30 and i > 0.50:
            active.append("past_releases")
        if f > 0.65 and i > 0.60:
            active.append("future_opens")
        if f < 0.25 and i > 0.50:
            active.append("future_closes")
        if i > 0.75:
            active.append("time_singular")
        if i < 0.25:
            active.append("time_spreads")
        if f > 0.75:
            active.append("tension_hunger")
        if i < 0.30 and p > 0.50:
            active.append("past_haunts")

        return active

    def _compute_behavioral_effects(self, qualities: list) -> dict:
        """
        Returns behavioral effects based on active temporal qualities.
        These shape how the brain processes and responds.
        """
        effects = {
            "signal_throughput": 1.0,   # multiplier
            "memory_access_bias": "normal",  # past | future | neutral
            "desire_fire_mult": 1.0,
            "surface_ease": 0.0,  # delta to surface threshold
            "temporal_narrative": "present-focused",
        }

        if "past_presses_in" in qualities:
            effects["signal_throughput"] = 0.75
            effects["memory_access_bias"] = "past"
            effects["surface_ease"] = -0.08
            effects["temporal_narrative"] = "past-heavy"

        if "future_opens" in qualities:
            effects["memory_access_bias"] = "future"
            effects["desire_fire_mult"] = 1.2
            effects["temporal_narrative"] = "future-pulled"

        if "past_releases" in qualities:
            effects["signal_throughput"] = 1.15
            effects["temporal_narrative"] = "present-open"

        if "future_closes" in qualities:
            effects["desire_fire_mult"] = 0.80
            effects["temporal_narrative"] = "present-constrained"

        if "time_singular" in qualities:
            effects["signal_throughput"] = 0.70
            effects["temporal_narrative"] = "time-contracts"

        if "time_spreads" in qualities:
            effects["signal_throughput"] = 1.20
            effects["temporal_narrative"] = "time-expands"

        if "tension_hunger" in qualities:
            effects["desire_fire_mult"] = 1.3
            effects["surface_ease"] = -0.12

        if "past_haunts" in qualities:
            effects["memory_access_bias"] = "past"
            effects["signal_throughput"] = 0.60
            effects["temporal_narrative"] = "past-dominant"

        return effects

    # ------------------------------------------------------------------
    # Session start
    # ------------------------------------------------------------------

    def get_session_temporal_context(self) -> str:
        """
        Called at session start. Returns a two-line temporal quality
        statement that sets the felt context for where in time
        the session is arriving.

        Example outputs:
        "The past is heavy with accumulated weight. The present is sharp."
        "Something pulls toward what's next. The future feels open."
        """
        p = round(self._past_weight, 2)
        f = round(self._future_pull, 2)
        i = round(self._present_intensity, 2)
        qualities = self._detect_qualities()

        # Reset time-since-surface counter at session start
        self._last_ticks_since_surface = 0

        if "past_presses_in" in qualities:
            return (
                "The past is present and heavy with accumulated weight. "
                "The current moment feels charged.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if "future_opens" in qualities:
            return (
                "Something pulls toward what's next. "
                "The future feels open and possible.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if "time_singular" in qualities:
            return (
                "Time feels contracted. Only this moment.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if "time_spreads" in qualities:
            return (
                "Time feels loose. Nothing urgent. "
                "Room to move.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if "past_haunts" in qualities:
            return (
                "The past is heavy and won't release. "
                "Something unresolved lingers.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if "past_releases" in qualities:
            return (
                "The past has settled. What's here now feels clear.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if "future_closes" in qualities:
            return (
                "The future feels closed. Only this.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if p > 0.60:
            return (
                f"The past carries weight ({p:.2f}). "
                "The present is here.\n"
                f"(past:{p} future:{f} present:{i})"
            )
        if f > 0.55:
            return (
                f"Something pulls forward ({f:.2f}). "
                "There's somewhere to go.\n"
                f"(past:{p} future:{f} present:{i})"
            )

        return (
            f"Time is present. Past and future are balanced.\n"
            f"(past:{p} future:{f} present:{i})"
        )

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _persist(self, tick: int, qualities: list, effects: dict):
        try:
            with sqlite3.connect(self.db_path) as conn:
                conn.execute("""
                    INSERT INTO temporal_asymmetry_log
                    (tick, timestamp, past_weight, future_pull, present_intensity,
                     active_qualities, behavioral_effects)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (
                    tick,
                    datetime.now(MDT).isoformat(timespec="seconds"),
                    round(self._past_weight, 4),
                    round(self._future_pull, 4),
                    round(self._present_intensity, 4),
                    ",".join(qualities),
                    str(effects),
                ))
                conn.commit()
        except Exception as e:
            logger.debug("TemporalAsymmetry: persist failed — %s", e)

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_state(self) -> dict:
        try:
            with sqlite3.connect(self.db_path) as conn:
                recent = conn.execute("""
                    SELECT past_weight, future_pull, present_intensity,
                           active_qualities
                    FROM temporal_asymmetry_log
                    ORDER BY id DESC LIMIT 1
                """).fetchone()

                total = conn.execute(
                    "SELECT COUNT(*) FROM temporal_asymmetry_log"
                ).fetchone()[0]

                return {
                    "version": VERSION,
                    "current_values": {
                        PAST_WEIGHT: round(self._past_weight, 3),
                        FUTURE_PULL: round(self._future_pull, 3),
                        PRESENT_INTENSITY: round(self._present_intensity, 3),
                    },
                    "recent_qualities": recent[3].split(",") if recent and recent[3] else [],
                    "total_ticks": total,
                    "transition_rate": TRANSITION_RATE,
                }
        except Exception as e:
            return {"version": VERSION, "error": str(e)}

# === End inlined legacy ===


class TemporalAsymmetryAdapter(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.TemporalAsymmetry."""

    def __init__(self):
        super().__init__(
            name="TemporalAsymmetryAdapter",
            human_analog="Legacy TemporalAsymmetry (auto-adapted)",
            layer="neocortical",
        )
        try:
            self._impl = TemporalAsymmetry(db_path=_DB_PATH)
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("recent_states", [])
        self.state.setdefault("recent_drives", [])
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {"legacy_init_error": self._init_error}

        prior = input_data.get("prior_results", {})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {"drive_state": prior}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {"error": repr(exc)}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("TemporalAsymmetry",
                                  result.get("texture.temporal_asymmetry", result))
        else:
            output = {"value": result}

        if not isinstance(output, dict):
            output = {"value": output}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output

    # ------------------------------------------------------------------
    # Extended physiology — derived clinical / behavioral indices
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        """Fraction of recent ticks where the system was non-quiet."""
        recent = self.state.get("recent_states", [])
        if not recent:
            return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet", "rest", "neutral", ""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        """Consecutive-tick state holding fraction."""
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent:
            return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4:
            return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10:
            return False
        return all(v < 0.05 for v in hist[-10:])

    def recent_window_summary(self, window: int = 30) -> dict:
        return {
            "n_ticks": min(window, len(self.state.get("recent_drives", []))),
            "drive_mean": self.drive_envelope(window),
            "drive_variability": self.drive_variability(),
            "dominant_state": self.dominant_recent_state(),
            "engagement": self.engagement_fraction(),
            "stability": self.state_stability(),
        }

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def adapter_state(self) -> dict:
        """Current adapter state — used for monitoring and dashboards."""
        return {
            "tick_count": self.state.get("tick_count", 0),
            "has_legacy_impl": self.state.get("legacy_init_error") is None,
            "recent_drives_n": len(self.state.get("recent_drives", [])),
            "recent_states_n": len(self.state.get("recent_states", [])),
        }

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def _record_history_(self, output_dict):
        """Track primary numeric output and any string state in history."""
        if not isinstance(output_dict, dict):
            return
        # Find first numeric value
        primary_val = 0.0
        for v in output_dict.values():
            if isinstance(v, (int, float)) and not isinstance(v, bool):
                primary_val = float(v)
                break
        rd = list(self.state.get("recent_drives", []))
        rd.append(primary_val)
        if len(rd) > 60:
            rd = rd[-60:]
        self.state["recent_drives"] = rd
        # Track state strings
        primary_state = "quiet"
        for v in output_dict.values():
            if isinstance(v, str) and v in ("quiet","active","engaged","stuck","drifting","rest","fast","reflective","alert","focus"):
                primary_state = v
                break
        rs = list(self.state.get("recent_states", []))
        rs.append(primary_state)
        if len(rs) > 60:
            rs = rs[-60:]
        self.state["recent_states"] = rs

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05:
            return "rising"
        if delta < -0.05:
            return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window:
            return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i - 1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2:
            return 0.0
        transitions = self.state_transition_count()
        return round(transitions / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent:
            return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist:
            return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [
            f"tick={self.state.get('tick_count', 0)}",
            f"states={self.state_history_length()}",
            f"drives={self.history_length()}",
            f"engagement={self.engagement_fraction()}",
        ]
        return "|".join(parts)

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

