"""
ThetaGammaCrossFrequencyBinding — CFC / Phase-Amplitude Coupling for Memory

NEURAL SUBSTRATE
================
Theta-gamma cross-frequency coupling (CFC) is the canonical mechanism
for binding multiple discrete items into a temporally-ordered sequence
in the hippocampus and prefrontal cortex. Lisman & Jensen 2013 ("The
Theta-Gamma Neural Code") formalized the model: each cycle of theta
(~4-8 Hz) gets subdivided into ~7 gamma sub-cycles (~30-100 Hz), and
each gamma cycle hosts the activity of one cell-assembly representing
one discrete item. This produces a temporally-ordered representation
of a sequence within a single theta cycle — the substrate of working
memory ordering and episodic-like binding.

The coupling is implemented as phase-amplitude coupling (PAC): gamma
amplitude is modulated by theta phase. Tort 2009 demonstrated PAC
strength increases during item-context association learning in
hippocampus, and Spellman 2017 showed hippocampal-prefrontal theta-gamma
coupling tracks spatial working memory performance.

Functional role: PAC is how the brain solves the "binding problem" for
sequential information. Disrupted theta-gamma coupling is a signature
of Alzheimer's disease, schizophrenia working-memory deficits, and
post-anesthesia memory impairment (Goutagny 2013 in AD models).

KEY FINDINGS
============
1. Theta-gamma neural code: discrete items represented in successive gamma cycles within a single theta cycle; substrate of sequence memory — [Lisman JE 2013, Neuron 77:1002, doi:10.1016/j.neuron.2013.03.007]
2. Theta-gamma phase-amplitude coupling increases during item-context association learning in hippocampus — [Tort AB 2009, PNAS 106:20942, doi:10.1073/pnas.0911331106]
3. Hippocampal-prefrontal theta-gamma coupling tracks spatial working memory performance — [Spellman T 2017, Nat Commun 8:1944, doi:10.1038/s41467-017-02108-9]
4. Canolty & Knight review of cross-frequency coupling as a mechanism for cortical computation and gating — [Canolty RT 2010, Trends Cogn Sci 14:506, doi:10.1016/j.tics.2010.09.001]
5. Theta-gamma coupling is disrupted in Alzheimer's disease mouse models; functional biomarker for memory impairment — [Goutagny R 2013, Eur J Neurosci 37:1947, doi:10.1111/ejn.12189]

INPUTS (from prior_results)
============================
- HippocampalCA1Dorsal.ca1d_drive (theta-band activity carrier)
- HippocampalCA3Dorsal.dca3_drive (gamma-generating recurrent network)
- MedialSeptum.theta_signal (or NucleusOfDiagonalBandVertical.theta_signal)
- PrelimbicCortex.pl_drive (PFC partner)
- DorsolateralPrefrontalCortex.dlpfc_drive (working memory)

OUTPUTS (to brain_runner enrichment)
=====================================
- pac_strength (0-1) — phase-amplitude coupling magnitude
- gamma_amplitude (0-1) — high-frequency activity envelope
- theta_phase_coherence (0-1) — alignment of theta phase
- sequence_binding_capacity (0-1) — how many items can be ordered
- item_load (0-1) — current items held in PAC
- cfc_state (str): "binding_active" | "high_load" | "decoupled" | "quiet"
"""

from brain.base_mechanism import BrainMechanism


class ThetaGammaCrossFrequencyBinding(BrainMechanism):
    """Theta-gamma PAC for sequential memory binding (Lisman 2013)."""

    BASELINE = 0.0
    SMOOTH = 0.20
    PAC_THRESHOLD = 0.40
    MAX_ITEMS = 7  # Lisman 2013 — ~7 gamma cycles per theta cycle

    def __init__(self):
        super().__init__(
            name="ThetaGammaCrossFrequencyBindingVariant",
            human_analog="Theta-gamma phase-amplitude coupling (Lisman 2013)",
            layer="integration",
        )
        self.state.setdefault("pac_strength", 0.0)
        self.state.setdefault("gamma_amplitude", 0.0)
        self.state.setdefault("theta_phase_coherence", 0.0)
        self.state.setdefault("sequence_binding_capacity", 0.0)
        self.state.setdefault("item_load", 0.0)
        self.state.setdefault("cfc_state", "quiet")
        self.state.setdefault("recent_states", [])
        self.state.setdefault("tick_count", 0)

    def _gamma_amplitude(self, ca3: float, ca1: float) -> float:
        """Gamma generated by CA3 recurrent network, expressed in CA1.
        Lisman 2013 — high-frequency oscillation carrier."""
        return min(1.0, ca3 * 0.55 + ca1 * 0.35)

    def _theta_coherence(self, theta_signal: float, pfc_drive: float) -> float:
        """Theta phase coherence — driven by medial septum pacemaker,
        amplified by PFC engagement (Spellman 2017 hipp-PFC coupling)."""
        if theta_signal < 0.20:
            return 0.0
        return min(1.0, theta_signal * 0.7 + pfc_drive * 0.3)

    def _pac_strength(self, gamma_amp: float, theta_coh: float) -> float:
        """Phase-amplitude coupling magnitude — multiplicative product
        (Tort 2009 — both must be high for PAC). PAC requires that
        gamma amplitude is modulated by theta phase, i.e. both are
        present and locked."""
        return min(1.0, gamma_amp * theta_coh * 1.6)

    def _binding_capacity(self, pac: float) -> float:
        """How many items can be ordered in current theta cycle.
        Capacity scales with PAC strength up to the Lisman-Jensen ~7 limit."""
        return min(1.0, pac * 1.2)

    def _item_load(self, prev_load: float, capacity: float,
                     dlpfc_drive: float) -> float:
        """Items currently held — slow-decaying integrator of working
        memory engagement multiplied by capacity (Spellman 2017)."""
        if capacity < 0.20:
            return prev_load * 0.85  # decay when no binding
        target = capacity * dlpfc_drive
        return prev_load * 0.75 + target * 0.25

    def _classify_state(self, pac: float, item_load: float,
                          theta_coh: float, gamma_amp: float) -> str:
        if theta_coh < 0.10 and gamma_amp < 0.10:
            return "quiet"
        if (theta_coh > 0.30) and (gamma_amp > 0.30) and pac < 0.20:
            return "decoupled"  # both present but not coupled
        if item_load > 0.60:
            return "high_load"
        if pac > self.PAC_THRESHOLD:
            return "binding_active"
        return "quiet"

    def _smooth(self, prev: float, target: float) -> float:
        return prev + (target - prev) * self.SMOOTH

    async def tick(self, input_data: dict) -> dict:
        prior = input_data.get("prior_results", {})

        ca3_data = prior.get("HippocampalCA3Dorsal", {})
        if not ca3_data:
            ca3_data = prior.get("HippocampalCA3", {})
        ca3 = float(ca3_data.get("dca3_drive",
                          ca3_data.get("ca3_output", 0.0)))

        ca1_data = prior.get("HippocampalCA1Dorsal", {})
        if not ca1_data:
            ca1_data = prior.get("HippocampalCA1", {})
        ca1 = float(ca1_data.get("ca1d_drive",
                          ca1_data.get("ca1_output", 0.0)))

        theta_data = prior.get("MedialSeptum", {})
        if not theta_data:
            theta_data = prior.get("NucleusOfDiagonalBandVertical", {})
        if not theta_data:
            theta_data = prior.get("DiagonalBandBroca", {})
        theta_signal = float(theta_data.get("theta_signal",
                                  theta_data.get("theta_drive", 0.0)))

        pl_data = prior.get("PrelimbicCortex", {})
        pl = float(pl_data.get("pl_drive", 0.0))

        dlpfc_data = prior.get("DorsolateralPrefrontalCortex", {})
        dlpfc = float(dlpfc_data.get("dlpfc_drive",
                            dlpfc_data.get("working_memory_signal", 0.0)))

        gamma_amp = self._gamma_amplitude(ca3, ca1)
        theta_coh = self._theta_coherence(theta_signal, max(pl, dlpfc))
        pac_target = self._pac_strength(gamma_amp, theta_coh)

        prev_pac = float(self.state.get("pac_strength", 0.0))
        pac = self._smooth(prev_pac, pac_target)

        capacity = self._binding_capacity(pac)
        prev_load = float(self.state.get("item_load", 0.0))
        item_load = self._item_load(prev_load, capacity, dlpfc)

        state = self._classify_state(pac, item_load, theta_coh, gamma_amp)

        recent = list(self.state.get("recent_states", []))
        recent.append(state)
        if len(recent) > 60:
            recent = recent[-60:]

        self.state["pac_strength"] = round(pac, 4)
        self.state["gamma_amplitude"] = round(gamma_amp, 4)
        self.state["theta_phase_coherence"] = round(theta_coh, 4)
        self.state["sequence_binding_capacity"] = round(capacity, 4)
        self.state["item_load"] = round(item_load, 4)
        self.state["cfc_state"] = state
        self.state["recent_states"] = recent
        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()

        return {
            "pac_strength": round(pac, 4),
            "gamma_amplitude": round(gamma_amp, 4),
            "theta_phase_coherence": round(theta_coh, 4),
            "sequence_binding_capacity": round(capacity, 4),
            "item_load": round(item_load, 4),
            "cfc_state": state,
        }

    def _ad_signature(self, recent_states: list) -> float:
        """Sustained 'decoupled' state = AD-like signature
        (Goutagny 2013 — disrupted PAC despite present oscillations)."""
        if not recent_states:
            return 0.0
        win = recent_states[-50:]
        d = sum(1 for s in win if s == "decoupled")
        return d / max(1, len(win))

    def _summary(self) -> dict:
        return {
            "pac": self.state.get("pac_strength", 0.0),
            "gamma": self.state.get("gamma_amplitude", 0.0),
            "theta": self.state.get("theta_phase_coherence", 0.0),
            "load": self.state.get("item_load", 0.0),
            "state": self.state.get("cfc_state", "quiet"),
        }

    # ------------------------------------------------------------------
    # Extended derived-state helpers
    # ------------------------------------------------------------------

    def engagement_fraction(self) -> float:
        recent = self.state.get("recent_states", [])
        if not recent: return 0.0
        engaged = sum(1 for s in recent if s not in ("quiet","rest","neutral",""))
        return round(engaged / len(recent), 4)

    def state_stability(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 1.0
        same = sum(1 for i in range(1, len(recent)) if recent[i] == recent[i-1])
        return round(same / (len(recent) - 1), 4)

    def dominant_recent_state(self) -> str:
        recent = self.state.get("recent_states", [])
        if not recent: return "quiet"
        from collections import Counter
        return Counter(recent).most_common(1)[0][0]

    def drive_envelope(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(sum(recent) / max(1, len(recent)), 4)

    def drive_variability(self) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 4: return 0.0
        recent = hist[-30:]
        mean = sum(recent) / len(recent)
        var = sum((v - mean) ** 2 for v in recent) / len(recent)
        return round(var ** 0.5, 4)

    def saturation_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v > 0.85 for v in hist[-10:])

    def quiescence_alert(self) -> bool:
        hist = self.state.get("recent_drives", [])
        if len(hist) < 10: return False
        return all(v < 0.05 for v in hist[-10:])

    def trend_direction(self, window: int = 10) -> str:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return "flat"
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        delta = second_half - first_half
        if delta > 0.05: return "rising"
        if delta < -0.05: return "falling"
        return "flat"

    def trend_magnitude(self, window: int = 10) -> float:
        hist = self.state.get("recent_drives", [])
        if len(hist) < window: return 0.0
        recent = hist[-window:]
        first_half = sum(recent[:window // 2]) / max(1, window // 2)
        second_half = sum(recent[window // 2:]) / max(1, window - window // 2)
        return round(abs(second_half - first_half), 4)

    def state_transition_count(self) -> int:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0
        return sum(1 for i in range(1, len(recent)) if recent[i] != recent[i-1])

    def state_transition_rate(self) -> float:
        recent = self.state.get("recent_states", [])
        if len(recent) < 2: return 0.0
        return round(self.state_transition_count() / (len(recent) - 1), 4)

    def state_distribution(self) -> dict:
        recent = self.state.get("recent_states", [])
        if not recent: return {}
        from collections import Counter
        c = Counter(recent)
        total = len(recent)
        return {state: round(count / total, 4) for state, count in c.items()}

    def drive_min_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(min(hist[-window:]), 4)

    def drive_max_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        return round(max(hist[-window:]), 4)

    def drive_range_recent(self, window: int = 30) -> float:
        hist = self.state.get("recent_drives", [])
        if not hist: return 0.0
        recent = hist[-window:]
        return round(max(recent) - min(recent), 4)

    def is_active(self) -> bool:
        return self.state.get("tick_count", 0) > 0

    def has_history(self) -> bool:
        return len(self.state.get("recent_drives", [])) > 0

    def history_length(self) -> int:
        return len(self.state.get("recent_drives", []))

    def state_history_length(self) -> int:
        return len(self.state.get("recent_states", []))

    def fingerprint(self) -> str:
        parts = [f"tick={self.state.get('tick_count', 0)}",
                 f"states={self.state_history_length()}",
                 f"drives={self.history_length()}",
                 f"engagement={self.engagement_fraction()}"]
        return "|".join(parts)

    def reset_history(self) -> None:
        self.state["recent_states"] = []
        self.state["recent_drives"] = []

    def is_healthy(self) -> bool:
        return (not self.saturation_alert()
                and not self.quiescence_alert()
                and self.state_stability() > 0.20)

    def summary(self) -> dict:
        return {
            "engagement_fraction": self.engagement_fraction(),
            "stability": self.state_stability(),
            "dominant_recent": self.dominant_recent_state(),
            "envelope": self.drive_envelope(),
            "variability": self.drive_variability(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
            "tick_count": self.state.get("tick_count", 0),
        }

    def diagnostics(self) -> dict:
        return {
            "is_active": self.is_active(),
            "is_healthy": self.is_healthy(),
            "has_history": self.has_history(),
            "tick_count": self.state.get("tick_count", 0),
            "history_length": self.history_length(),
            "transition_rate": self.state_transition_rate(),
            "trend": self.trend_direction(),
            "trend_magnitude": self.trend_magnitude(),
            "drive_range": self.drive_range_recent(),
            "saturation_alert": self.saturation_alert(),
            "quiescence_alert": self.quiescence_alert(),
        }

