#!/usr/bin/env python3
"""
brain_root_adapter_generator.py
================================
Generates BrainMechanism adapters for the phenomenological/integrative
mechanism files sitting loose at brain/ root (NOT in the 5 layer subdirs).

Skips:
  - files identical to a legacy/ counterpart (already covered by
    scripts/legacy_adapter_generator.py)
  - files that don't define any class with a process() method
  - infrastructure files (base_mechanism, bootstrap, core_loop, etc.)

Adapter imports `from brain.{module} import {class}` (NOT legacy).
"""
from __future__ import annotations

import ast
import filecmp
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BRAIN_ROOT = REPO / "brain"
LEGACY_ROOT = REPO / "legacy"

# Infra / pipeline files — not mechanisms, skip
INFRA_SKIP = {
    "base_mechanism.py", "bootstrap.py", "core_loop.py",
    "brain_integration.py", "foundational_run_order.py",
    "root_mechanism_router.py",
    # heavy multi-class infra
    "distortion.py", "pipeline_deepening.py", "reconstruction.py",
    "pirp.py", "knowledge_graph.py", "chroma_store.py",
    "vector_pipeline.py", "vector_retrieval.py",
    "nineteen_orb_orchestrator.py", "ghost_cognition.py",
    "identity_self_model.py", "phantom_reinforcement_drift.py",
    "llm.py", "llm_router.py", "eval_suite.py", "layer_registry.py",
    "constraint_fields.py", "vectorized_identity_fields.py",
}

LAYER_BY_KEYWORD = [
    ("Cerebell", "subcortical"),
    ("Thalam", "subcortical"),
    ("Striat", "subcortical"),
    ("Hypothalam", "subcortical"),
    ("Hippocamp", "limbic"),
    ("Amygdal", "limbic"),
    ("Cingul", "limbic"),
    ("Septal", "limbic"),
    ("Cortex", "neocortical"),
    ("Cortical", "neocortical"),
    ("Frontal", "neocortical"),
    ("Parietal", "neocortical"),
    ("Temporal", "neocortical"),
    ("Occipital", "neocortical"),
    ("Visual", "neocortical"),
    ("Auditory", "neocortical"),
    ("Motor", "neocortical"),
    ("Brainstem", "foundational"),
    ("Reticul", "foundational"),
    ("Vagal", "foundational"),
    # phenomenological / integrative themes
    ("Identity", "integration"),
    ("Council", "integration"),
    ("Witness", "integration"),
    ("Coalition", "integration"),
    ("Confabulation", "integration"),
    ("Distortion", "integration"),
    ("Drift", "integration"),
    ("Soul", "integration"),
    ("Phenomen", "integration"),
    ("Narrative", "neocortical"),
    ("Theory", "neocortical"),
    ("Memory", "limbic"),
    ("Grief", "limbic"),
    ("Bond", "limbic"),
    ("Longing", "limbic"),
    ("Mood", "limbic"),
    ("Desire", "limbic"),
    ("Curiosity", "integration"),
    ("Plasticity", "limbic"),
    ("Becoming", "limbic"),
    ("Dream", "integration"),
    ("Future", "integration"),
    ("Belief", "integration"),
    ("Existential", "integration"),
    ("Knowing", "integration"),
    ("Metacognitive", "integration"),
]
DEFAULT_LAYER = "integration"


ADAPTER_TEMPLATE = '''"""
{adapter_class} — Auto-generated BrainMechanism adapter (from brain/ root)

WRAPS:
    brain.{module}.{cls}

LAYER:
    {layer}

NOTE: Generated by scripts/brain_root_adapter_generator.py. The wrapped
class uses the old process(pirp_context) pattern; this adapter exposes
it via async tick(input_data) so the brain_runner can register it.
"""
import os
from pathlib import Path

from brain.base_mechanism import BrainMechanism
from brain.{module} import {cls}


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".openclaw" / "workspace")))
    / "brain" / "agent.db"
)


class {adapter_class}(BrainMechanism):
    """Adapter: BrainMechanism wrapper around brain.{cls}."""

    def __init__(self):
        super().__init__(
            name="{registry_name}",
            human_analog="brain/ root {cls} (auto-adapted)",
            layer="{layer}",
        )
        try:
            self._impl = {cls}({ctor_args})
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {{"legacy_init_error": self._init_error}}
        prior = input_data.get("prior_results", {{}})
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {{"drive_state": prior}}
        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {{"error": repr(exc)}}
        if isinstance(result, dict):
            output = result.get("{registry_name}",
                                  result.get("{module}", result))
        else:
            output = {{"value": result}}
        if not isinstance(output, dict):
            output = {{"value": output}}
        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output
'''


def find_classes(file_path: Path):
    try:
        tree = ast.parse(file_path.read_text(encoding="utf-8"))
    except Exception:
        return []
    out = []
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        if node.name.startswith("_"):
            continue
        ctor_kind = "noargs"
        has_process = False
        has_init = False
        for item in node.body:
            if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if item.name == "__init__":
                    has_init = True
                    args = item.args.args[1:]
                    defaults = item.args.defaults
                    n_required = len(args) - len(defaults)
                    if n_required == 0 and len(args) <= 1:
                        ctor_kind = "noargs" if len(args) == 0 else "db_path_opt"
                    elif n_required == 1 and len(args) == 1:
                        if args[0].arg in ("db_path", "db", "path"):
                            ctor_kind = "db_path_req"
                        else:
                            ctor_kind = "unknown"
                    else:
                        ctor_kind = "unknown"
                elif item.name == "process":
                    if len(item.args.args) >= 2:  # self + pirp_context
                        has_process = True
        if has_process and ctor_kind != "unknown":
            out.append((node.name, ctor_kind))
    return out


def assign_layer(class_name: str) -> str:
    for kw, layer in LAYER_BY_KEYWORD:
        if kw in class_name:
            return layer
    return DEFAULT_LAYER


def ctor_args_for(kind: str) -> str:
    if kind in ("db_path_req", "db_path_opt"):
        return "db_path=_DB_PATH"
    return ""


def main() -> int:
    n_files = 0
    n_skipped_identical = 0
    n_skipped_infra = 0
    n_skipped_no_class = 0
    n_written = 0
    layer_counts: dict[str, int] = {}

    # First pass — collect candidates
    candidates: list[tuple[Path, str, str]] = []
    for path in sorted(BRAIN_ROOT.glob("*.py")):
        if not path.is_file():
            continue
        if path.name in INFRA_SKIP:
            n_skipped_infra += 1
            continue
        n_files += 1
        # Skip files identical to legacy counterpart — already covered
        legacy_match = LEGACY_ROOT / path.name
        if legacy_match.exists() and filecmp.cmp(path, legacy_match,
                                                       shallow=False):
            n_skipped_identical += 1
            continue
        cls_list = find_classes(path)
        if not cls_list:
            n_skipped_no_class += 1
            continue
        for cls, kind in cls_list:
            candidates.append((path, cls, kind))

    # Disambiguation: track which class names will be present after legacy
    # conversion (each class in legacy/ already has an adapter under
    # `{Class}Adapter.py` in some layer). If our brain/ root candidate has
    # the same class name, suffix our adapter to avoid registry collision.
    def legacy_adapter_exists(cls_name: str) -> bool:
        for layer in ("foundational", "limbic", "subcortical",
                          "neocortical", "integration"):
            if (REPO / "brain" / layer / f"{cls_name}Adapter.py").exists():
                return True
        return False

    for path, cls, kind in candidates:
        layer = assign_layer(cls)
        if legacy_adapter_exists(cls):
            adapter_class = f"{cls}_FromBrainRoot_Adapter"
            registry_name = f"{cls}_BrainRoot"
        else:
            adapter_class = f"{cls}Adapter"
            registry_name = cls
        adapter_filename = f"{adapter_class}.py"
        target_dir = REPO / "brain" / layer
        target_path = target_dir / adapter_filename
        if target_path.exists():
            continue

        adapter_src = ADAPTER_TEMPLATE.format(
            adapter_class=adapter_class,
            module=path.stem,
            cls=cls,
            layer=layer,
            registry_name=registry_name,
            ctor_args=ctor_args_for(kind),
        )
        target_dir.mkdir(parents=True, exist_ok=True)
        target_path.write_text(adapter_src, encoding="utf-8")
        n_written += 1
        layer_counts[layer] = layer_counts.get(layer, 0) + 1
        print(f"[WROTE] brain/{layer}/{adapter_filename}  (wraps brain.{path.stem}.{cls})")

    print()
    print("=" * 60)
    print(f"Scanned brain/ root files:        {n_files}")
    print(f"Skipped — infra:                   {n_skipped_infra}")
    print(f"Skipped — identical to legacy/:    {n_skipped_identical}")
    print(f"Skipped — no process() class:      {n_skipped_no_class}")
    print(f"Adapters written:                  {n_written}")
    print()
    print("By layer:")
    for layer, count in sorted(layer_counts.items()):
        print(f"  {layer:14s} {count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
