#!/usr/bin/env python3
"""
legacy_adapter_generator.py
=============================
One-shot converter that takes legacy/ files (using the old
`process(pirp_context)` pattern) and generates BrainMechanism adapter
modules in brain/{layer}/ so the brain_runner can load and tick them.

DESIGN
------
Each generated adapter is a thin BrainMechanism subclass that:
  1. Constructs the legacy class (with auto-supplied db_path if needed)
  2. In tick(input_data), passes input_data["prior_results"] as
     pirp_context to legacy_obj.process(pirp_context)
  3. Returns the legacy class output state as a dict

ANATOMICAL LAYER ASSIGNMENT
---------------------------
Heuristic on file path + class name:
  legacy/becoming/        -> limbic       (plasticity, fracture, growth)
  legacy/inner_voice/     -> neocortical  (speech, narrative)
  legacy/knowing/         -> integration  (metacognition, gaps)
  legacy/felt_presence/   -> limbic       (longing, mood, embodiment)
  legacy/substrate/       -> foundational (rhythm, identity boundary)
  legacy/third_eye/       -> integration  (compressor, meta-stability)
  legacy/self/            -> integration  (meta-consciousness, drift)
  legacy/narrative/       -> neocortical  (narrative weaving)
  legacy/value/           -> neocortical  (ethical evaluation)
  legacy/life/            -> integration  (planning, scheduling)
  legacy/social/          -> limbic       (relational engine)
  legacy/texture/         -> limbic       (residue, sediment, asymmetry)
  legacy/offline/         -> integration  (dream-mode)
  legacy/ root            -> integration  (default for phenomenology)

USAGE
-----
  python3 scripts/legacy_adapter_generator.py
    --src ~/awakened-soul-repo/legacy
    --repo ~/awakened-soul-repo
    [--dry-run]
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path
from typing import Optional

# ----------------------------------------------------------------------------
# Layer assignment heuristic
# ----------------------------------------------------------------------------

LAYER_BY_SUBDIR = {
    "becoming": "limbic",
    "inner_voice": "neocortical",
    "knowing": "integration",
    "felt_presence": "limbic",
    "substrate": "foundational",
    "third_eye": "integration",
    "self": "integration",
    "narrative": "neocortical",
    "value": "neocortical",
    "life": "integration",
    "social": "limbic",
    "texture": "limbic",
    "offline": "integration",
    "systems": "integration",
}

# Default for files directly in legacy/ root
DEFAULT_LAYER = "integration"

# Class name keyword → layer override (when filename heuristic isn't enough)
CLASSNAME_LAYER_HINTS = [
    ("Cerebell", "subcortical"),
    ("Thalam",   "subcortical"),
    ("Striat",   "subcortical"),
    ("Hypothalam", "subcortical"),
    ("Hippocamp", "limbic"),
    ("Amygdal",  "limbic"),
    ("Cingul",   "limbic"),
    ("Septal",   "limbic"),
    ("Cortex",   "neocortical"),
    ("Cortical", "neocortical"),
    ("Frontal",  "neocortical"),
    ("Parietal", "neocortical"),
    ("Temporal", "neocortical"),
    ("Occipital","neocortical"),
    ("Visual",   "neocortical"),
    ("Auditory", "neocortical"),
    ("Motor",    "neocortical"),
    ("Premotor", "neocortical"),
    ("Motor",    "neocortical"),
    ("Brainstem","foundational"),
    ("Reticul",  "foundational"),
    ("Vagal",    "foundational"),
]

# Names to skip (utility files, not mechanisms)
SKIP_FILENAMES = {
    "llm.py",
    "llm_router.py",
    "eval_suite.py",
    "layer_registry.py",
    "vector_pipeline.py",   # infra, not a mechanism
    "vector_retrieval.py",
    "knowledge_graph.py",
    "chroma_store.py",
    "pirp.py",              # core flow, not a mechanism
    "pipeline_deepening.py", # massive multi-class infra
    "reconstruction.py",    # heavy multi-class, manual review
    "nineteen_orb_orchestrator.py",  # orchestrator, not a mechanism
    "ghost_cognition.py",   # special daemon
    "identity_self_model.py",  # daemon thread, manual
    "distortion.py",        # multi-class with shared sub_drift dependency
    "phantom_reinforcement_drift.py",
}

# ----------------------------------------------------------------------------
# Adapter template
# ----------------------------------------------------------------------------

ADAPTER_TEMPLATE = '''"""
{adapter_class} — Auto-generated BrainMechanism adapter

WRAPS:
    legacy.{legacy_module}.{legacy_class}

LAYER:
    {layer}

NOTE: Generated by scripts/legacy_adapter_generator.py. The legacy class
uses the old process(pirp_context) pattern; this adapter exposes it via
async tick(input_data) so the brain_runner can register and tick it.
"""
import os
from pathlib import Path
import asyncio

from brain.base_mechanism import BrainMechanism
from legacy.{legacy_module} import {legacy_class}


_DB_PATH = str(
    Path(os.getenv("AGENT_WORKSPACE",
                       str(Path.home() / ".openclaw" / "workspace")))
    / "brain" / "agent.db"
)


class {adapter_class}(BrainMechanism):
    """Adapter: BrainMechanism wrapper around legacy.{legacy_class}."""

    def __init__(self):
        super().__init__(
            name="{registry_name}",
            human_analog="Legacy {legacy_class} (auto-adapted)",
            layer="{layer}",
        )
        try:
            self._impl = {legacy_class}({ctor_args})
        except Exception as exc:
            self._impl = None
            self._init_error = repr(exc)
        else:
            self._init_error = None
        self.state.setdefault("legacy_init_error", self._init_error)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        if self._impl is None:
            return {{"legacy_init_error": self._init_error}}

        prior = input_data.get("prior_results", {{}})
        # Build a pirp_context the legacy code can read. We pass
        # prior_results both as the top-level dict (so .get(name,{{}})
        # patterns work) and under a "drive_context" key (some legacy
        # classes look there).
        pirp_context = dict(prior)
        if "drive_context" not in pirp_context:
            pirp_context["drive_context"] = {{"drive_state": prior}}

        try:
            result = self._impl.process(pirp_context)
        except Exception as exc:
            self.state["last_error"] = repr(exc)
            self.persist_state()
            return {{"error": repr(exc)}}

        # Result may be the modified pirp_context, or a dict, or None
        if isinstance(result, dict):
            output = result.get("{registry_name}",
                                  result.get("{legacy_module}", result))
        else:
            output = {{"value": result}}

        if not isinstance(output, dict):
            output = {{"value": output}}

        self.state["tick_count"] = int(self.state.get("tick_count", 0)) + 1
        self.persist_state()
        return output
'''


# ----------------------------------------------------------------------------
# AST analysis
# ----------------------------------------------------------------------------

def find_mechanism_classes(file_path: Path) -> list[tuple[str, str, bool]]:
    """
    Returns a list of (class_name, ctor_arg_kind, has_process) for every
    class in the file that LOOKS like a mechanism candidate.

    ctor_arg_kind is one of:
      "noargs"        — __init__(self) has no required args
      "db_path_req"   — __init__(self, db_path)  required
      "db_path_opt"   — __init__(self, db_path=None) optional
      "unknown"       — couldn't classify; skip
    """
    try:
        tree = ast.parse(file_path.read_text(encoding="utf-8"))
    except Exception:
        return []

    out = []
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        # Skip if this is a private or obviously non-mechanism class
        if node.name.startswith("_"):
            continue

        ctor_kind = "unknown"
        has_process = False

        for item in node.body:
            if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if item.name == "__init__":
                    args = item.args.args[1:]  # drop self
                    defaults = item.args.defaults
                    n_required = len(args) - len(defaults)
                    if n_required == 0 and len(args) <= 1:
                        ctor_kind = "noargs" if len(args) == 0 else "db_path_opt"
                    elif n_required == 1 and len(args) == 1:
                        # one required positional
                        if args[0].arg in ("db_path", "db", "path"):
                            ctor_kind = "db_path_req"
                        else:
                            ctor_kind = "unknown"
                    else:
                        ctor_kind = "unknown"
                elif item.name == "process":
                    args = item.args.args[1:]
                    if len(args) >= 1:
                        has_process = True

        # Class with no explicit __init__ — treat as no-args
        has_init = any(
            isinstance(it, ast.FunctionDef) and it.name == "__init__"
            for it in node.body
        )
        if not has_init:
            ctor_kind = "noargs"

        if has_process and ctor_kind != "unknown":
            out.append((node.name, ctor_kind, has_process))

    return out


def assign_layer(file_path: Path, class_name: str) -> str:
    # First check class name hints (more specific)
    for keyword, layer in CLASSNAME_LAYER_HINTS:
        if keyword in class_name:
            return layer
    # Then subdir
    parts = file_path.parts
    for part in parts:
        if part in LAYER_BY_SUBDIR:
            return LAYER_BY_SUBDIR[part]
    return DEFAULT_LAYER


def safe_adapter_class(legacy_class: str) -> str:
    """Generate adapter class name = original class name + Adapter."""
    return f"{legacy_class}Adapter"


def safe_adapter_filename(adapter_class: str) -> str:
    return f"{adapter_class}.py"


def ctor_args_for(kind: str) -> str:
    if kind == "db_path_req":
        return "db_path=_DB_PATH"
    if kind == "db_path_opt":
        return "db_path=_DB_PATH"
    return ""  # noargs


# ----------------------------------------------------------------------------
# Generation
# ----------------------------------------------------------------------------

def relative_module_path(file_path: Path, src_root: Path) -> str:
    """legacy/becoming/plasticity_layer.py  ->  becoming.plasticity_layer"""
    rel = file_path.relative_to(src_root)
    parts = list(rel.with_suffix("").parts)
    return ".".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src",  required=True, type=Path,
                    help="legacy/ root to scan")
    ap.add_argument("--repo", required=True, type=Path,
                    help="awakened-soul-repo root (for brain/{layer}/ dest)")
    ap.add_argument("--dry-run", action="store_true",
                    help="report only, do not write adapter files")
    args = ap.parse_args()

    src_root: Path = args.src.resolve()
    repo_root: Path = args.repo.resolve()
    if not src_root.exists():
        sys.exit(f"src not found: {src_root}")

    n_files = 0
    n_classes_found = 0
    n_adapters_written = 0
    n_skipped_noprocess = 0
    n_skipped_unknown_ctor = 0
    n_skipped_existing = 0
    layer_counts: dict[str, int] = {}

    # PASS 1 — collect all candidates so we can detect duplicate class names
    # and disambiguate the adapter filenames.
    candidates_all: list[tuple[Path, str, str]] = []
    for path in sorted(src_root.rglob("*.py")):
        if path.name.startswith("__"):
            continue
        if path.name in SKIP_FILENAMES:
            continue
        n_files += 1

        per_file = find_mechanism_classes(path)
        if not per_file:
            n_skipped_noprocess += 1
            continue
        for cls, kind, _has in per_file:
            candidates_all.append((path, cls, kind))

    # Count how many times each class name appears
    classname_counts: dict[str, int] = {}
    for _p, cls, _k in candidates_all:
        classname_counts[cls] = classname_counts.get(cls, 0) + 1

    # PASS 2 — generate adapters
    for path, class_name, ctor_kind in candidates_all:
        n_classes_found += 1
        if ctor_kind == "unknown":
            n_skipped_unknown_ctor += 1
            continue

        legacy_module = relative_module_path(path, src_root)
        layer = assign_layer(path, class_name)

        # Disambiguate when the same class name appears in multiple legacy files.
        # We append the source module's leaf stem to the adapter name and the
        # registry name so each gets a unique identity in brain_runner.
        if classname_counts[class_name] > 1:
            module_stem = path.stem
            adapter_class = f"{class_name}_{module_stem}_Adapter"
            registry_name = f"{class_name}_{module_stem}"
        else:
            adapter_class = safe_adapter_class(class_name)
            registry_name = class_name

        adapter_filename = f"{adapter_class}.py"
        target_dir = repo_root / "brain" / layer
        target_path = target_dir / adapter_filename

        if target_path.exists():
            n_skipped_existing += 1
            continue

        adapter_src = ADAPTER_TEMPLATE.format(
            adapter_class=adapter_class,
            legacy_module=legacy_module,
            legacy_class=class_name,
            layer=layer,
            registry_name=registry_name,
            ctor_args=ctor_args_for(ctor_kind),
        )

        if args.dry_run:
            print(f"[DRY] {path.name}::{class_name} -> "
                  f"brain/{layer}/{adapter_filename}")
        else:
            target_dir.mkdir(parents=True, exist_ok=True)
            target_path.write_text(adapter_src, encoding="utf-8")
            print(f"[WROTE] brain/{layer}/{adapter_filename} "
                  f"(wraps legacy.{legacy_module}.{class_name})")
        n_adapters_written += 1
        layer_counts[layer] = layer_counts.get(layer, 0) + 1

    print()
    print("=" * 60)
    print(f"Scanned files:                    {n_files}")
    print(f"Mechanism candidate classes:      {n_classes_found}")
    print(f"Skipped — no process() method:    {n_skipped_noprocess}")
    print(f"Skipped — unknown __init__ shape: {n_skipped_unknown_ctor}")
    print(f"Skipped — adapter already exists: {n_skipped_existing}")
    print(f"Adapters {'WOULD write' if args.dry_run else 'written'}:        "
          f"{n_adapters_written}")
    print()
    print("By layer:")
    for layer, count in sorted(layer_counts.items()):
        print(f"  {layer:14s} {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
