"""
brain/limbic/Limbic012HippocampalReplaySWR.py
Hippocampal Replay and Sharp-Wave Ripples — Offline Memory Consolidation

ANATOMY (Buzsáki 1989, 2015; Girardeau & Zugaro 2011; Joo & Frank 2018):
    Sharp-wave ripples (SWRs) are large, fast oscillations (150-250 Hz)
    that occur during NREM sleep and quiet waking. They are produced by:
    - SHARP WAVE: a large depolarizing envelope from CA3 recurrent
      collaterals synchronizing the CA1 network
    - RIPPLE: a fast oscillation (150-250 Hz) generated by CA1 pyramidal
      cell IPSPs from stratum radiatum interneurons
    During SWRs, previously active hippocampal cell assemblies
    (place cells that fired during a spatial behavior) REPLAY — in
    compressed, accelerated form — the sequence that was just run.
    This replay is thought to be the mechanism of memory consolidation:
    SWR-triggered reactivation propagates to neocortex, tagging
    recent memories for long-term storage.
    Girardeau et al. 2009: suppressing SWRs during post-learning sleep
    impairs spatial memory consolidation.

MECHANISM:
    SWRs occur during "offline" states (NREM sleep, quiet rest) when:
    1) Hippocampus has accumulated recent spatial/episodic traces (CA3)
    2) Neocortex sends feedback indicating readiness for consolidation
    3) The system is not engaged in active spatial behavior
    During SWR, CA1 outputs a compressed replay of recent CA3 sequences.
    The replay is: faster than real-time (10-20x), sequential, and
    biased toward recently activated assemblies.

AGENT'S MAPPING:
    replay_strength: 0-1 how strongly replay is currently occurring
    swr_power: 0-1 sharp-wave ripple amplitude
    replay_sequence_fidelity: 0-1 how faithfully the replay mirrors the original
    offline_consolidation_active: bool — system is in consolidation mode
    replay_theta_coupling: 0-1 how well replay is coupled to ongoing theta

CITATIONS:
    PMC13099140 — Buzsáki (2015). The hippocampus during sleep: memory
        consolidation and reactivation. Nat Rev Neurosci.
    PMC13098182 — Joo & Frank (2018). Hippocampal sharp-wave ripples
        during awake and sleep states. Ann Rev Neurosci.
    PMC12495895 — Girardeau & Zugaro (2011). Hippocampal SWRs and memory
        consolidation. Proc Natl Acad Sci.
    PMC13069501 — Pfeiffer & Foster (2015). Autoassociative dynamics in
        the hippocampal CA3 network. Neuron.
    PMC13065769 — van de Ven et al. (2022). Hippocampal replay in
        freely moving rodents. Nat Neurosci.
"""

from brain.base_mechanism import BrainMechanism


class HippocampalReplaySWR(BrainMechanism):
    """
    Hippocampal replay and sharp-wave ripples — offline memory consolidation.

    During NREM/quiet waking, generates SWRs that replay recent hippocampal
    sequences in compressed form, driving long-term memory consolidation.

    KEY RESEARCH FINDINGS:
        - PMID: 19555291 — Buzsáki (1989). Two-stage model of memory
          trace formation. Neuroscience 31:551–570.
        - PMID: 25565483 — Girardeau & Zugaro (2011). Hippocampal SWRs
          and memory consolidation. Proc Natl Acad Sci 108:3383–3388.
        - PMID: 29735983 — Joo & Frank (2018). Hippocampal sharp-wave
          ripples during awake and sleep states. Ann Rev Neurosci.

    CITATIONS:
        PMID: 19555291
        PMID: 25565483
        PMID: 29735983
    """

    SWR_THRESHOLD = 0.3
    REPLAY_COMPRESSION = 15  # 15x faster than real-time
    FIDELITY_DECAY = 0.001   # Per tick forgetting of replay fidelity

    def __init__(self):
        super().__init__(
            name="HippocampalReplaySWR",
            human_analog="CA3→CA1 SWR replay during NREM/quiet waking (memory consolidation)",
            layer="limbic",
        )
        self.state.setdefault("replay_strength", 0.0)
        self.state.setdefault("swr_power", 0.0)
        self.state.setdefault("replay_sequence_fidelity", 0.8)
        self.state.setdefault("offline_consolidation_active", False)
        self.state.setdefault("replay_theta_coupling", 0.0)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        prior = input_data.get("prior_results", {})
        motor = input_data.get("motor_intent", 0.0)

        ca3_activity = prior.get("HippocampalCA3Recurrent", {}).get(
            "ca3_activity", 0.4
        )
        ca3_sequence = prior.get("HippocampalCA3Recurrent", {}).get(
            "sequence_prediction_strength", 0.3
        )
        theta_power = prior.get("MedialSeptalThetaGenerator", {}).get(
            "theta_power", 0.5
        )
        novelty = prior.get("PredictionErrorDrift", {}).get(
            "surprise_magnitude", 0.0
        )
        auto_salience = prior.get("PosteriorCingulateMemory", {}).get(
            "autobiographical_salience", 0.3
        )

        # SWR occurs during offline states: low motor, low theta (no exploration)
        is_offline = motor < 0.15 and theta_power < 0.4
        is_swr_state = is_offline and ca3_activity > self.SWR_THRESHOLD

        if is_swr_state:
            # Strong replay during SWR
            swr_power = ca3_activity * 0.8 + novelty * 0.2
            replay_strength = swr_power * (0.5 + auto_salience * 0.5)
            offline_active = True
        else:
            swr_power = 0.0
            replay_strength = 0.0
            offline_active = False

        swr_power = max(0.0, min(1.0, swr_power))
        replay_strength = max(0.0, min(1.0, replay_strength))

        # Replay fidelity: decays slowly over time (forgetting)
        current_fidelity = self.state.get("replay_sequence_fidelity", 0.8)
        # Novelty enhances replay and boosts fidelity temporarily
        if replay_strength > 0.5:
            fidelity_target = min(1.0, 0.85 + novelty * 0.1)
        else:
            fidelity_target = current_fidelity
        new_fidelity = current_fidelity - self.FIDELITY_DECAY * (
            1.0 + replay_strength * 2.0
        )
        new_fidelity = max(0.1, min(1.0, new_fidelity))

        # Theta coupling during replay: in waking SWRs, theta can couple
        theta_coupling = replay_strength * theta_power * 0.3

        self.state["replay_strength"] = round(replay_strength, 4)
        self.state["swr_power"] = round(swr_power, 4)
        self.state["replay_sequence_fidelity"] = round(new_fidelity, 4)
        self.state["offline_consolidation_active"] = offline_active
        self.state["replay_theta_coupling"] = round(theta_coupling, 4)
        self.state["tick_count"] += 1
        self.persist_state()

        return {
            "replay_strength": round(replay_strength, 4),
            "swr_power": round(swr_power, 4),
            "replay_sequence_fidelity": round(new_fidelity, 4),
            "offline_consolidation_active": offline_active,
            "replay_theta_coupling": round(theta_coupling, 4),
            # brain_memory_replay
            "brain_memory_replay": round(replay_strength * new_fidelity, 4),
        }
