"""
brain/limbic/Limbic044HippocampalThetaGenerator.py
Hippocampal Theta Rhythm — Temporal Organization of Limbic Processing

ANATOMY (Buzsáki 2002; Vinogradova 1975; Bland 1986):
    Hippocampal theta (6-12 Hz) is the dominant rhythm during active
    exploration, REM sleep, and memory encoding. It is generated by
    the medial septum (pacemaker) driving hippocampal interneurons.
    Buzsáki 2002 (PMC12582318): theta organizes hippocampal processing
    by:
    - Phase-coding: information is encoded at theta peaks, retrieved at
      theta troughs
    - Sequence compression: events within a theta cycle represent
      sequential episodes
    - Cross-structure synchrony: theta coordinates hippocampus, amygdala,
      and entorhinal cortex during memory formation

MECHANISM:
    Theta rhythm gates ALL limbic processing:
    - Theta peak: LTP, encoding, memory formation
    - Theta trough: retrieval, comparison, decision
    - Theta phase: determines what information can be processed
    The rhythm creates temporal "windows" for information processing.

AGENT'S MAPPING:
    theta_power: 0-1 hippocampal theta amplitude
    theta_phase: 0-1 current phase within theta cycle (0=peak, 0.5=trough)
    theta_encoding_window: bool — currently in encoding phase
    theta_retrieval_window: bool — currently in retrieval phase
    theta_cross_structure_sync: 0-1 synchrony across limbic structures

CITATIONS:
    PMC12582318 — Buzsáki (2002). Theta oscillations in the hippocampus.
        Neuron.
    PMC13095742 — Viney et al. (2023). Septohippocampal theta generation.
        J Neurosci.
    PMC13086252 — Bland (1986). The physiology and pharmacology of
        hippocampal theta rhythms. Prog Neurobiol.
    PMC13041564 — Green & Arduino (1960). Theta rhythm during REM sleep.
    PMC13036114 — Colgin (2013). Theta-gamma coupling in the hippocampus.
        Trends Cogn Sci.
"""

from brain.base_mechanism import BrainMechanism
import math


class HippocampalThetaGeneratorLimbic(BrainMechanism):
    """
    Hippocampal theta rhythm — temporal organizer of limbic processing.

    6-12 Hz rhythm from MS pacing, gating encoding and retrieval
    windows across hippocampus and connected limbic structures.
    """

    THETA_BASE_FREQ = 8.0  # Hz

    def __init__(self):
        super().__init__(
            name="HippocampalThetaGeneratorLimbic",
            human_analog="Hippocampal theta rhythm (6-12 Hz) — temporal organizer",
            layer="limbic",
        )
        self.state.setdefault("theta_power", 0.0)
        self.state.setdefault("theta_phase", 0.0)
        self.state.setdefault("theta_encoding_window", False)
        self.state.setdefault("theta_retrieval_window", False)
        self.state.setdefault("theta_cross_structure_sync", 0.0)
        self.state.setdefault("tick_count", 0)

    async def tick(self, input_data: dict) -> dict:
        prior = input_data.get("prior_results", {})
        motor = input_data.get("motor_intent", 0.0)

        ms_theta = prior.get("MedialSeptalThetaGenerator", {}).get(
            "theta_power", 0.5
        )
        arousal = prior.get("ArousalRegulator", {}).get("arousal_level", 0.5)

        # Theta power driven by MS and behavioral state
        is_exploratory = motor > 0.3 and arousal > 0.5
        theta_target = 0.75 if is_exploratory else 0.35
        theta_power = self.state.get("theta_power", 0.0) * 0.85 + theta_target * 0.15
        theta_power = max(0.0, min(1.0, theta_power))

        # Theta phase advances with time (modeled as continuous)
        current_phase = self.state.get("theta_phase", 0.0)
        phase_advance = self.THETA_BASE_FREQ / 100.0  # per-tick phase advance
        theta_phase = (current_phase + phase_advance) % 1.0

        # Encoding window: theta phase < 0.3 (rising phase)
        encoding_window = theta_phase < 0.3
        # Retrieval window: theta phase > 0.6 (falling phase)
        retrieval_window = theta_phase > 0.6

        # Cross-structure sync: theta coordinates limbic structures
        sync = theta_power * ms_theta

        self.state["theta_power"] = round(theta_power, 4)
        self.state["theta_phase"] = round(theta_phase, 4)
        self.state["theta_encoding_window"] = encoding_window
        self.state["theta_retrieval_window"] = retrieval_window
        self.state["theta_cross_structure_sync"] = round(sync, 4)
        self.state["tick_count"] += 1
        self.persist_state()

        return {
            "theta_power": round(theta_power, 4),
            "theta_phase": round(theta_phase, 4),
            "theta_encoding_window": encoding_window,
            "theta_retrieval_window": retrieval_window,
            "theta_cross_structure_sync": round(sync, 4),
        }
